"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .albuserror import AlbusError
from typing import Any, TYPE_CHECKING

from albus_sdk.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .albusdefaulterror import AlbusDefaultError
    from .errbadrequest import ErrBadRequest, ErrBadRequestData
    from .errconflict import ErrConflict, ErrConflictData
    from .errinsufficientcredit import ErrInsufficientCredit, ErrInsufficientCreditData
    from .errinvocationcanceled import ErrInvocationCanceled, ErrInvocationCanceledData
    from .errinvocationfailed import ErrInvocationFailed, ErrInvocationFailedData
    from .errlocked import ErrLocked, ErrLockedData
    from .errnotfound import ErrNotFound, ErrNotFoundData
    from .errquotaexceeded import ErrQuotaExceeded, ErrQuotaExceededData
    from .errtimeout import ErrTimeout, ErrTimeoutData
    from .errunauthorized import ErrUnauthorized, ErrUnauthorizedData
    from .errunavailable import ErrUnavailable, ErrUnavailableData
    from .healthresponse_error import HealthResponseError, HealthResponseErrorData
    from .no_response_error import NoResponseError
    from .responsevalidationerror import ResponseValidationError

__all__ = [
    "AlbusDefaultError",
    "AlbusError",
    "ErrBadRequest",
    "ErrBadRequestData",
    "ErrConflict",
    "ErrConflictData",
    "ErrInsufficientCredit",
    "ErrInsufficientCreditData",
    "ErrInvocationCanceled",
    "ErrInvocationCanceledData",
    "ErrInvocationFailed",
    "ErrInvocationFailedData",
    "ErrLocked",
    "ErrLockedData",
    "ErrNotFound",
    "ErrNotFoundData",
    "ErrQuotaExceeded",
    "ErrQuotaExceededData",
    "ErrTimeout",
    "ErrTimeoutData",
    "ErrUnauthorized",
    "ErrUnauthorizedData",
    "ErrUnavailable",
    "ErrUnavailableData",
    "HealthResponseError",
    "HealthResponseErrorData",
    "NoResponseError",
    "ResponseValidationError",
]

_dynamic_imports: dict[str, str] = {
    "AlbusDefaultError": ".albusdefaulterror",
    "ErrBadRequest": ".errbadrequest",
    "ErrBadRequestData": ".errbadrequest",
    "ErrConflict": ".errconflict",
    "ErrConflictData": ".errconflict",
    "ErrInsufficientCredit": ".errinsufficientcredit",
    "ErrInsufficientCreditData": ".errinsufficientcredit",
    "ErrInvocationCanceled": ".errinvocationcanceled",
    "ErrInvocationCanceledData": ".errinvocationcanceled",
    "ErrInvocationFailed": ".errinvocationfailed",
    "ErrInvocationFailedData": ".errinvocationfailed",
    "ErrLocked": ".errlocked",
    "ErrLockedData": ".errlocked",
    "ErrNotFound": ".errnotfound",
    "ErrNotFoundData": ".errnotfound",
    "ErrQuotaExceeded": ".errquotaexceeded",
    "ErrQuotaExceededData": ".errquotaexceeded",
    "ErrTimeout": ".errtimeout",
    "ErrTimeoutData": ".errtimeout",
    "ErrUnauthorized": ".errunauthorized",
    "ErrUnauthorizedData": ".errunauthorized",
    "ErrUnavailable": ".errunavailable",
    "ErrUnavailableData": ".errunavailable",
    "HealthResponseError": ".healthresponse_error",
    "HealthResponseErrorData": ".healthresponse_error",
    "NoResponseError": ".no_response_error",
    "ResponseValidationError": ".responsevalidationerror",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
