"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from albus_sdk.errors import AlbusError
from albus_sdk.types import BaseModel
from dataclasses import dataclass, field
import httpx
from typing import Optional


class ErrInsufficientCreditData(BaseModel):
    message: str
    r"""Human-readable error message"""


@dataclass(unsafe_hash=True)
class ErrInsufficientCredit(AlbusError):
    data: ErrInsufficientCreditData = field(hash=False)

    def __init__(
        self,
        data: ErrInsufficientCreditData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
