"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from albus_sdk.errors import AlbusError
from albus_sdk.types import BaseModel
from dataclasses import dataclass, field
import httpx
from typing import Optional


class HealthResponseErrorData(BaseModel):
    status: str


@dataclass(unsafe_hash=True)
class HealthResponseError(AlbusError):
    data: HealthResponseErrorData = field(hash=False)

    def __init__(
        self,
        data: HealthResponseErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
