"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import Any, TYPE_CHECKING

from albus_sdk.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .deletesecret import DeleteSecretRequest, DeleteSecretRequestTypedDict
    from .deletesession import DeleteSessionRequest, DeleteSessionRequestTypedDict
    from .deletetoken import DeleteTokenRequest, DeleteTokenRequestTypedDict
    from .getagent import GetAgentRequest, GetAgentRequestTypedDict
    from .getagentrevision import (
        GetAgentRevisionRequest,
        GetAgentRevisionRequestTypedDict,
    )
    from .getsecret import GetSecretRequest, GetSecretRequestTypedDict
    from .getsession import GetSessionRequest, GetSessionRequestTypedDict
    from .getsessionaudit import GetSessionAuditRequest, GetSessionAuditRequestTypedDict
    from .gettoken import GetTokenRequest, GetTokenRequestTypedDict
    from .runsession import (
        RunSessionRequest,
        RunSessionRequestTypedDict,
        RunSessionResponse,
        RunSessionResponseTypedDict,
    )
    from .updatesecret import UpdateSecretRequest, UpdateSecretRequestTypedDict

__all__ = [
    "DeleteSecretRequest",
    "DeleteSecretRequestTypedDict",
    "DeleteSessionRequest",
    "DeleteSessionRequestTypedDict",
    "DeleteTokenRequest",
    "DeleteTokenRequestTypedDict",
    "GetAgentRequest",
    "GetAgentRequestTypedDict",
    "GetAgentRevisionRequest",
    "GetAgentRevisionRequestTypedDict",
    "GetSecretRequest",
    "GetSecretRequestTypedDict",
    "GetSessionAuditRequest",
    "GetSessionAuditRequestTypedDict",
    "GetSessionRequest",
    "GetSessionRequestTypedDict",
    "GetTokenRequest",
    "GetTokenRequestTypedDict",
    "RunSessionRequest",
    "RunSessionRequestTypedDict",
    "RunSessionResponse",
    "RunSessionResponseTypedDict",
    "UpdateSecretRequest",
    "UpdateSecretRequestTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "DeleteSecretRequest": ".deletesecret",
    "DeleteSecretRequestTypedDict": ".deletesecret",
    "DeleteSessionRequest": ".deletesession",
    "DeleteSessionRequestTypedDict": ".deletesession",
    "DeleteTokenRequest": ".deletetoken",
    "DeleteTokenRequestTypedDict": ".deletetoken",
    "GetAgentRequest": ".getagent",
    "GetAgentRequestTypedDict": ".getagent",
    "GetAgentRevisionRequest": ".getagentrevision",
    "GetAgentRevisionRequestTypedDict": ".getagentrevision",
    "GetSecretRequest": ".getsecret",
    "GetSecretRequestTypedDict": ".getsecret",
    "GetSessionRequest": ".getsession",
    "GetSessionRequestTypedDict": ".getsession",
    "GetSessionAuditRequest": ".getsessionaudit",
    "GetSessionAuditRequestTypedDict": ".getsessionaudit",
    "GetTokenRequest": ".gettoken",
    "GetTokenRequestTypedDict": ".gettoken",
    "RunSessionRequest": ".runsession",
    "RunSessionRequestTypedDict": ".runsession",
    "RunSessionResponse": ".runsession",
    "RunSessionResponseTypedDict": ".runsession",
    "UpdateSecretRequest": ".updatesecret",
    "UpdateSecretRequestTypedDict": ".updatesecret",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
