"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import Any, TYPE_CHECKING

from albus_sdk.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .cancelsession import CancelSessionRequest, CancelSessionRequestTypedDict
    from .deletememory import DeleteMemoryRequest, DeleteMemoryRequestTypedDict
    from .deletememorygroup import (
        DeleteMemoryGroupRequest,
        DeleteMemoryGroupRequestTypedDict,
    )
    from .deletesecret import DeleteSecretRequest, DeleteSecretRequestTypedDict
    from .deletesession import DeleteSessionRequest, DeleteSessionRequestTypedDict
    from .deletetoken import DeleteTokenRequest, DeleteTokenRequestTypedDict
    from .getagent import GetAgentRequest, GetAgentRequestTypedDict
    from .getagentrevision import (
        GetAgentRevisionRequest,
        GetAgentRevisionRequestTypedDict,
    )
    from .getsecret import GetSecretRequest, GetSecretRequestTypedDict
    from .getsession import GetSessionRequest, GetSessionRequestTypedDict
    from .getsessionaudit import GetSessionAuditRequest, GetSessionAuditRequestTypedDict
    from .gettoken import GetTokenRequest, GetTokenRequestTypedDict
    from .gettrace import (
        Attempts,
        GetTraceRequest,
        GetTraceRequestTypedDict,
        GetTraceResponse,
        GetTraceResponseTypedDict,
    )
    from .listmemories import ListMemoriesRequest, ListMemoriesRequestTypedDict
    from .listmemorygroups import (
        ListMemoryGroupsRequest,
        ListMemoryGroupsRequestTypedDict,
    )
    from .listtraces import ListTracesRequest, ListTracesRequestTypedDict
    from .runsession import (
        RunSessionRequest,
        RunSessionRequestTypedDict,
        RunSessionResponse,
        RunSessionResponseTypedDict,
    )
    from .updatesecret import UpdateSecretRequest, UpdateSecretRequestTypedDict

__all__ = [
    "Attempts",
    "CancelSessionRequest",
    "CancelSessionRequestTypedDict",
    "DeleteMemoryGroupRequest",
    "DeleteMemoryGroupRequestTypedDict",
    "DeleteMemoryRequest",
    "DeleteMemoryRequestTypedDict",
    "DeleteSecretRequest",
    "DeleteSecretRequestTypedDict",
    "DeleteSessionRequest",
    "DeleteSessionRequestTypedDict",
    "DeleteTokenRequest",
    "DeleteTokenRequestTypedDict",
    "GetAgentRequest",
    "GetAgentRequestTypedDict",
    "GetAgentRevisionRequest",
    "GetAgentRevisionRequestTypedDict",
    "GetSecretRequest",
    "GetSecretRequestTypedDict",
    "GetSessionAuditRequest",
    "GetSessionAuditRequestTypedDict",
    "GetSessionRequest",
    "GetSessionRequestTypedDict",
    "GetTokenRequest",
    "GetTokenRequestTypedDict",
    "GetTraceRequest",
    "GetTraceRequestTypedDict",
    "GetTraceResponse",
    "GetTraceResponseTypedDict",
    "ListMemoriesRequest",
    "ListMemoriesRequestTypedDict",
    "ListMemoryGroupsRequest",
    "ListMemoryGroupsRequestTypedDict",
    "ListTracesRequest",
    "ListTracesRequestTypedDict",
    "RunSessionRequest",
    "RunSessionRequestTypedDict",
    "RunSessionResponse",
    "RunSessionResponseTypedDict",
    "UpdateSecretRequest",
    "UpdateSecretRequestTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "CancelSessionRequest": ".cancelsession",
    "CancelSessionRequestTypedDict": ".cancelsession",
    "DeleteMemoryRequest": ".deletememory",
    "DeleteMemoryRequestTypedDict": ".deletememory",
    "DeleteMemoryGroupRequest": ".deletememorygroup",
    "DeleteMemoryGroupRequestTypedDict": ".deletememorygroup",
    "DeleteSecretRequest": ".deletesecret",
    "DeleteSecretRequestTypedDict": ".deletesecret",
    "DeleteSessionRequest": ".deletesession",
    "DeleteSessionRequestTypedDict": ".deletesession",
    "DeleteTokenRequest": ".deletetoken",
    "DeleteTokenRequestTypedDict": ".deletetoken",
    "GetAgentRequest": ".getagent",
    "GetAgentRequestTypedDict": ".getagent",
    "GetAgentRevisionRequest": ".getagentrevision",
    "GetAgentRevisionRequestTypedDict": ".getagentrevision",
    "GetSecretRequest": ".getsecret",
    "GetSecretRequestTypedDict": ".getsecret",
    "GetSessionRequest": ".getsession",
    "GetSessionRequestTypedDict": ".getsession",
    "GetSessionAuditRequest": ".getsessionaudit",
    "GetSessionAuditRequestTypedDict": ".getsessionaudit",
    "GetTokenRequest": ".gettoken",
    "GetTokenRequestTypedDict": ".gettoken",
    "Attempts": ".gettrace",
    "GetTraceRequest": ".gettrace",
    "GetTraceRequestTypedDict": ".gettrace",
    "GetTraceResponse": ".gettrace",
    "GetTraceResponseTypedDict": ".gettrace",
    "ListMemoriesRequest": ".listmemories",
    "ListMemoriesRequestTypedDict": ".listmemories",
    "ListMemoryGroupsRequest": ".listmemorygroups",
    "ListMemoryGroupsRequestTypedDict": ".listmemorygroups",
    "ListTracesRequest": ".listtraces",
    "ListTracesRequestTypedDict": ".listtraces",
    "RunSessionRequest": ".runsession",
    "RunSessionRequestTypedDict": ".runsession",
    "RunSessionResponse": ".runsession",
    "RunSessionResponseTypedDict": ".runsession",
    "UpdateSecretRequest": ".updatesecret",
    "UpdateSecretRequestTypedDict": ".updatesecret",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
