"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from albus_sdk.types import BaseModel, UNSET_SENTINEL
from albus_sdk.utils import FieldMetadata, HeaderMetadata, PathParamMetadata
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class DeleteMemoryGlobalsTypedDict(TypedDict):
    x_albus_organization: NotRequired[str]
    r"""The id of the organization the request acts on, which must be one the caller belongs to. Defaults to the organization the caller joined first. Ignored for API keys, which are bound to one organization.

    """


class DeleteMemoryGlobals(BaseModel):
    x_albus_organization: Annotated[
        Optional[str],
        pydantic.Field(alias="X-Albus-Organization"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = None
    r"""The id of the organization the request acts on, which must be one the caller belongs to. Defaults to the organization the caller joined first. Ignored for API keys, which are bound to one organization.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["X-Albus-Organization"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class DeleteMemoryRequestTypedDict(TypedDict):
    group: str
    r"""The memory group to read or delete — the `memory.group` value the agents sharing those memories run with.

    """
    id: str
    r"""The memory's identifier, as returned by `GET /memorygroups/{group}`.

    """


class DeleteMemoryRequest(BaseModel):
    group: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The memory group to read or delete — the `memory.group` value the agents sharing those memories run with.

    """

    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The memory's identifier, as returned by `GET /memorygroups/{group}`.

    """
