"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from albus_sdk.types import BaseModel
from albus_sdk.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class DeleteMemoryRequestTypedDict(TypedDict):
    group: str
    r"""Memory group to read or delete, matching the agent's `memory.group`.

    """
    id: str
    r"""Identifier of the memory to delete."""


class DeleteMemoryRequest(BaseModel):
    group: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Memory group to read or delete, matching the agent's `memory.group`.

    """

    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Identifier of the memory to delete."""
