"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from albus_sdk.types import BaseModel
from albus_sdk.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class DeleteSessionRequestTypedDict(TypedDict):
    id: str
    r"""Client-provided session identifier. Use the same value across requests to continue the same agent session."""


class DeleteSessionRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Client-provided session identifier. Use the same value across requests to continue the same agent session."""
