"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from albus_sdk.types import BaseModel, UNSET_SENTINEL
from albus_sdk.utils import FieldMetadata, QueryParamMetadata
from datetime import datetime
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetSpendRequestTypedDict(TypedDict):
    since: NotRequired[datetime]
    r"""Include usage from the UTC day containing this time onward. Defaults to 31 days before `until`.

    """
    until: NotRequired[datetime]
    r"""Include usage through the end of the UTC day containing this time. Defaults to now and must be after `since`.

    """


class GetSpendRequest(BaseModel):
    since: Annotated[
        Optional[datetime],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Include usage from the UTC day containing this time onward. Defaults to 31 days before `until`.

    """

    until: Annotated[
        Optional[datetime],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Include usage through the end of the UTC day containing this time. Defaults to now and must be after `since`.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["since", "until"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
