"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from albus_sdk.models import traceresponse as models_traceresponse
from albus_sdk.types import BaseModel, UNSET_SENTINEL
from albus_sdk.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
from pydantic import model_serializer
from typing import Dict, List, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


Attempts = Literal[
    "final",
    "all",
]
r"""Attempts whose spans to return. `final` returns only the latest; `all` includes earlier spans marked `superseded`.

"""


class GetTraceRequestTypedDict(TypedDict):
    invocation_key: str
    r"""Invocation key sent or returned in the `Idempotency-Key` header.

    """
    payloads: NotRequired[bool]
    r"""Whether to include span inputs and outputs. Disabling payloads raises the maximum `limit` to 500. Use the same value on every page.

    """
    attempts: NotRequired[Attempts]
    r"""Attempts whose spans to return. `final` returns only the latest; `all` includes earlier spans marked `superseded`.

    """
    after: NotRequired[str]
    r"""Continue after this cursor. For list responses, pass the preceding page's `next_cursor`; for session messages, pass the preceding page's last message `cursor`.

    """
    limit: NotRequired[int]
    r"""Maximum spans to return. Defaults to 25 with payloads and 500 without; these are also the respective maximums.

    """


class GetTraceRequest(BaseModel):
    invocation_key: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Invocation key sent or returned in the `Idempotency-Key` header.

    """

    payloads: Annotated[
        Optional[bool],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = True
    r"""Whether to include span inputs and outputs. Disabling payloads raises the maximum `limit` to 500. Use the same value on every page.

    """

    attempts: Annotated[
        Optional[Attempts],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = "final"
    r"""Attempts whose spans to return. `final` returns only the latest; `all` includes earlier spans marked `superseded`.

    """

    after: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Continue after this cursor. For list responses, pass the preceding page's `next_cursor`; for session messages, pass the preceding page's last message `cursor`.

    """

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Maximum spans to return. Defaults to 25 with payloads and 500 without; these are also the respective maximums.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["payloads", "attempts", "after", "limit"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetTraceResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: models_traceresponse.TraceResponseTypedDict


class GetTraceResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: models_traceresponse.TraceResponse
