"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from albus_sdk.models import tracestatus as models_tracestatus
from albus_sdk.types import BaseModel, UNSET_SENTINEL
from albus_sdk.utils import FieldMetadata, QueryParamMetadata
from datetime import datetime
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ListTracesRequestTypedDict(TypedDict):
    agent_name: NotRequired[str]
    r"""Return only invocations of this agent (e.g. \"support-triage\"). Invocations with no recorded agent name are not matched.

    """
    agent_revision: NotRequired[str]
    r"""Return only invocations of this exact agent revision (e.g. \"a1b2c3d4\"). Combines with `agent_name`. Invocations with no recorded revision are not matched.

    """
    status: NotRequired[models_tracestatus.TraceStatus]
    r"""Return only invocations with this outcome. An invocation whose spans have aged out is still matched by the outcome it recorded.

    """
    session_id: NotRequired[str]
    r"""Return only invocations of this session — the session identifier you ran it with. A session you do not have is a `404`.

    """
    since: NotRequired[datetime]
    r"""Return only invocations that started at or after this time. Defaults to 31 days ago; pass it to search further back.

    """
    until: NotRequired[datetime]
    r"""Return only invocations that started at or before this time. Defaults to now, and must be after `since`; an earlier `until` is a `400`.

    """
    after: NotRequired[str]
    r"""Opaque pagination cursor. Return only items positioned after it; pass a value obtained from a previous page to fetch the next one.

    """
    limit: NotRequired[int]
    r"""Maximum number of traces to return. A page can be shorter, so page while `next_cursor` is present.

    """


class ListTracesRequest(BaseModel):
    agent_name: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Return only invocations of this agent (e.g. \"support-triage\"). Invocations with no recorded agent name are not matched.

    """

    agent_revision: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Return only invocations of this exact agent revision (e.g. \"a1b2c3d4\"). Combines with `agent_name`. Invocations with no recorded revision are not matched.

    """

    status: Annotated[
        Optional[models_tracestatus.TraceStatus],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Return only invocations with this outcome. An invocation whose spans have aged out is still matched by the outcome it recorded.

    """

    session_id: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Return only invocations of this session — the session identifier you ran it with. A session you do not have is a `404`.

    """

    since: Annotated[
        Optional[datetime],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Return only invocations that started at or after this time. Defaults to 31 days ago; pass it to search further back.

    """

    until: Annotated[
        Optional[datetime],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Return only invocations that started at or before this time. Defaults to now, and must be after `since`; an earlier `until` is a `400`.

    """

    after: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Opaque pagination cursor. Return only items positioned after it; pass a value obtained from a previous page to fetch the next one.

    """

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 10
    r"""Maximum number of traces to return. A page can be shorter, so page while `next_cursor` is present.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "agent_name",
                "agent_revision",
                "status",
                "session_id",
                "since",
                "until",
                "after",
                "limit",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
