"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from albus_sdk.models import sessionstate as models_sessionstate
from albus_sdk.types import BaseModel, UNSET_SENTINEL
from albus_sdk.utils import FieldMetadata, QueryParamMetadata
from datetime import datetime
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ListSessionsRequestTypedDict(TypedDict):
    agent_name: NotRequired[str]
    r"""Return only sessions that ran this agent (e.g. \"support-triage\").

    """
    agent_revision: NotRequired[str]
    r"""Return only sessions that ran this agent revision (e.g. \"a1b2c3d4\"). Requires `agent_name`.

    """
    status: NotRequired[models_sessionstate.SessionState]
    r"""Return only sessions with an invocation in this state. `DONE` matches a successful invocation.

    """
    invocation_key: NotRequired[str]
    r"""Return only the session containing this invocation.

    """
    since: NotRequired[datetime]
    r"""Return only sessions with an invocation that started at or after this time. Defaults to 31 days ago.

    """
    until: NotRequired[datetime]
    r"""Return only sessions with an invocation that started at or before this time. Defaults to now and must be after `since`.

    """
    after: NotRequired[str]
    r"""Continue after this cursor. For list responses, pass the preceding page's `next_cursor`; for session messages, pass the preceding page's last message `cursor`.

    """
    limit: NotRequired[int]
    r"""Maximum number of sessions to return."""


class ListSessionsRequest(BaseModel):
    agent_name: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Return only sessions that ran this agent (e.g. \"support-triage\").

    """

    agent_revision: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Return only sessions that ran this agent revision (e.g. \"a1b2c3d4\"). Requires `agent_name`.

    """

    status: Annotated[
        Optional[models_sessionstate.SessionState],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Return only sessions with an invocation in this state. `DONE` matches a successful invocation.

    """

    invocation_key: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Return only the session containing this invocation.

    """

    since: Annotated[
        Optional[datetime],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Return only sessions with an invocation that started at or after this time. Defaults to 31 days ago.

    """

    until: Annotated[
        Optional[datetime],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Return only sessions with an invocation that started at or before this time. Defaults to now and must be after `since`.

    """

    after: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Continue after this cursor. For list responses, pass the preceding page's `next_cursor`; for session messages, pass the preceding page's last message `cursor`.

    """

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 25
    r"""Maximum number of sessions to return."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "agent_name",
                "agent_revision",
                "status",
                "invocation_key",
                "since",
                "until",
                "after",
                "limit",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
