"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from albus_sdk.types import BaseModel, UNSET_SENTINEL
from albus_sdk.utils import FieldMetadata, QueryParamMetadata
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ListMemoriesRequestTypedDict(TypedDict):
    group: str
    r"""The memory group to read or delete — the `memory.group` value the agents sharing those memories run with.

    """
    after: NotRequired[str]
    r"""Opaque pagination cursor. Return only items positioned after it; pass a value obtained from a previous page to fetch the next one.

    """
    limit: NotRequired[int]
    r"""Maximum number of items to return."""


class ListMemoriesRequest(BaseModel):
    group: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]
    r"""The memory group to read or delete — the `memory.group` value the agents sharing those memories run with.

    """

    after: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Opaque pagination cursor. Return only items positioned after it; pass a value obtained from a previous page to fetch the next one.

    """

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 100
    r"""Maximum number of items to return."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["after", "limit"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
