"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from albus_sdk.models import (
    runsessionrequest as models_runsessionrequest,
    runsessionresponse as models_runsessionresponse,
)
from albus_sdk.types import BaseModel, UNSET_SENTINEL
from albus_sdk.utils import (
    FieldMetadata,
    HeaderMetadata,
    PathParamMetadata,
    QueryParamMetadata,
    RequestMetadata,
)
import pydantic
from pydantic import model_serializer
from typing import Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class RunSessionRequestTypedDict(TypedDict):
    id: str
    r"""Client-provided session identifier. Reuse it to continue the session.

    """
    body: models_runsessionrequest.RunSessionRequestTypedDict
    invocation_key: NotRequired[str]
    r"""Names the invocation and makes identical requests safe to retry. Reuse with a different body returns `409`. When omitted, the response returns a generated key and the request is not retry-safe.

    """
    wait_timeout_seconds: NotRequired[int]
    r"""Wait up to this many seconds for the assistant response. Omit to wait 30 minutes; use 0 to return once accepted. A timeout does not stop the invocation.

    """


class RunSessionRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Client-provided session identifier. Reuse it to continue the session.

    """

    body: Annotated[
        models_runsessionrequest.RunSessionRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    invocation_key: Annotated[
        Optional[str],
        pydantic.Field(alias="Idempotency-Key"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = None
    r"""Names the invocation and makes identical requests safe to retry. Reuse with a different body returns `409`. When omitted, the response returns a generated key and the request is not retry-safe.

    """

    wait_timeout_seconds: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 1800
    r"""Wait up to this many seconds for the assistant response. Omit to wait 30 minutes; use 0 to return once accepted. A timeout does not stop the invocation.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["invocation_key", "wait_timeout_seconds"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class RunSessionResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: models_runsessionresponse.RunSessionResponseTypedDict


class RunSessionResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: models_runsessionresponse.RunSessionResponse
