"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from albus_sdk.models import (
    setorganizationmemberrolerequest as models_setorganizationmemberrolerequest,
)
from albus_sdk.types import BaseModel
from albus_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class SetOrganizationMemberRoleRequestTypedDict(TypedDict):
    user_id: str
    r"""The member's user identifier."""
    body: models_setorganizationmemberrolerequest.SetOrganizationMemberRoleRequestTypedDict


class SetOrganizationMemberRoleRequest(BaseModel):
    user_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The member's user identifier."""

    body: Annotated[
        models_setorganizationmemberrolerequest.SetOrganizationMemberRoleRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
