"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from albus_sdk.models import updatesecretrequest as models_updatesecretrequest
from albus_sdk.types import BaseModel
from albus_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UpdateSecretRequestTypedDict(TypedDict):
    name: str
    body: models_updatesecretrequest.UpdateSecretRequestTypedDict


class UpdateSecretRequest(BaseModel):
    name: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    body: Annotated[
        models_updatesecretrequest.UpdateSecretRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
