"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import AsyncBaseSDK, BaseSDK
from albus_sdk import errors, models, operations, utils
from albus_sdk._hooks import HookContext
from albus_sdk.types import OptionalNullable, UNSET
from albus_sdk.utils import get_security_from_env
from albus_sdk.utils.unmarshal_json_response import unmarshal_json_response
from typing import Any, Optional


class Agents(BaseSDK):
    r"""Inspect the agents that have run in your organization."""

    def list_agents(
        self,
    ) -> models.ListAgentsResponse:
        r"""List agents

        Lists the agents that have run in your organization, each with its latest revision.


        If set, this operation will use either `bearer_auth` or `api_key` from the global security.

        """
        url_variables = None
        base_url = self._get_url(None, url_variables)
        req = self._build_request(
            method="GET",
            path="/agents",
            base_url=base_url,
            url_variables=url_variables,
            request=None,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            allowed_fields=["bearer_auth", "api_key"],
            timeout_ms=self.sdk_configuration.timeout_ms,
        )

        retry_config = None

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="listAgents",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=["Agents"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=None,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.ListAgentsResponse, http_res)
        if utils.match_response(http_res, "401", "application/json"):
            response_data = unmarshal_json_response(
                errors.ErrUnauthorizedData, http_res
            )
            raise errors.ErrUnauthorized(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.AlbusDefaultError("Unexpected response received", http_res)

    def get_agent(
        self,
        *,
        name: str,
    ) -> models.Agent:
        r"""Get an agent by name

        Returns the agent with the given name, its current revision, and the list of all its revisions newest first.


        If set, this operation will use either `bearer_auth` or `api_key` from the global security.

        :param name: The agent's name.
        """
        url_variables = None
        base_url = self._get_url(None, url_variables)

        request = operations.GetAgentRequest(
            name=name,
        )

        req = self._build_request(
            method="GET",
            path="/agents/{name}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            allowed_fields=["bearer_auth", "api_key"],
            timeout_ms=self.sdk_configuration.timeout_ms,
        )

        retry_config = None

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="getAgent",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=["Agents"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=None,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.Agent, http_res)
        if utils.match_response(http_res, "401", "application/json"):
            response_data = unmarshal_json_response(
                errors.ErrUnauthorizedData, http_res
            )
            raise errors.ErrUnauthorized(response_data, http_res)
        if utils.match_response(http_res, "404", "application/json"):
            response_data = unmarshal_json_response(errors.ErrNotFoundData, http_res)
            raise errors.ErrNotFound(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.AlbusDefaultError("Unexpected response received", http_res)

    def get_agent_revision(
        self,
        *,
        name: str,
        revision: str,
    ) -> models.AgentRevision:
        r"""Get a specific revision of an agent

        Returns the full configuration of one revision of an agent — its model, tools, instructions, and MCP servers.


        If set, this operation will use either `bearer_auth` or `api_key` from the global security.

        :param name: The agent's name.
        :param revision: The agent revision to fetch.
        """
        url_variables = None
        base_url = self._get_url(None, url_variables)

        request = operations.GetAgentRevisionRequest(
            name=name,
            revision=revision,
        )

        req = self._build_request(
            method="GET",
            path="/agents/{name}/revisions/{revision}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            allowed_fields=["bearer_auth", "api_key"],
            timeout_ms=self.sdk_configuration.timeout_ms,
        )

        retry_config = None

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="getAgentRevision",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=["Agents"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=None,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.AgentRevision, http_res)
        if utils.match_response(http_res, "401", "application/json"):
            response_data = unmarshal_json_response(
                errors.ErrUnauthorizedData, http_res
            )
            raise errors.ErrUnauthorized(response_data, http_res)
        if utils.match_response(http_res, "404", "application/json"):
            response_data = unmarshal_json_response(errors.ErrNotFoundData, http_res)
            raise errors.ErrNotFound(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.AlbusDefaultError("Unexpected response received", http_res)


class AsyncAgents(AsyncBaseSDK):
    r"""Inspect the agents that have run in your organization."""

    async def list_agents(
        self,
    ) -> models.ListAgentsResponse:
        r"""List agents

        Lists the agents that have run in your organization, each with its latest revision.


        If set, this operation will use either `bearer_auth` or `api_key` from the global security.

        """
        url_variables = None
        base_url = self._get_url(None, url_variables)
        req = self._build_request_async(
            method="GET",
            path="/agents",
            base_url=base_url,
            url_variables=url_variables,
            request=None,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            allowed_fields=["bearer_auth", "api_key"],
            timeout_ms=self.sdk_configuration.timeout_ms,
        )

        retry_config = None

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="listAgents",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=["Agents"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=None,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.ListAgentsResponse, http_res)
        if utils.match_response(http_res, "401", "application/json"):
            response_data = unmarshal_json_response(
                errors.ErrUnauthorizedData, http_res
            )
            raise errors.ErrUnauthorized(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.AlbusDefaultError("Unexpected response received", http_res)

    async def get_agent(
        self,
        *,
        name: str,
    ) -> models.Agent:
        r"""Get an agent by name

        Returns the agent with the given name, its current revision, and the list of all its revisions newest first.


        If set, this operation will use either `bearer_auth` or `api_key` from the global security.

        :param name: The agent's name.
        """
        url_variables = None
        base_url = self._get_url(None, url_variables)

        request = operations.GetAgentRequest(
            name=name,
        )

        req = self._build_request_async(
            method="GET",
            path="/agents/{name}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            allowed_fields=["bearer_auth", "api_key"],
            timeout_ms=self.sdk_configuration.timeout_ms,
        )

        retry_config = None

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="getAgent",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=["Agents"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=None,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.Agent, http_res)
        if utils.match_response(http_res, "401", "application/json"):
            response_data = unmarshal_json_response(
                errors.ErrUnauthorizedData, http_res
            )
            raise errors.ErrUnauthorized(response_data, http_res)
        if utils.match_response(http_res, "404", "application/json"):
            response_data = unmarshal_json_response(errors.ErrNotFoundData, http_res)
            raise errors.ErrNotFound(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.AlbusDefaultError("Unexpected response received", http_res)

    async def get_agent_revision(
        self,
        *,
        name: str,
        revision: str,
    ) -> models.AgentRevision:
        r"""Get a specific revision of an agent

        Returns the full configuration of one revision of an agent — its model, tools, instructions, and MCP servers.


        If set, this operation will use either `bearer_auth` or `api_key` from the global security.

        :param name: The agent's name.
        :param revision: The agent revision to fetch.
        """
        url_variables = None
        base_url = self._get_url(None, url_variables)

        request = operations.GetAgentRevisionRequest(
            name=name,
            revision=revision,
        )

        req = self._build_request_async(
            method="GET",
            path="/agents/{name}/revisions/{revision}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            allowed_fields=["bearer_auth", "api_key"],
            timeout_ms=self.sdk_configuration.timeout_ms,
        )

        retry_config = None

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="getAgentRevision",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=["Agents"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=None,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.AgentRevision, http_res)
        if utils.match_response(http_res, "401", "application/json"):
            response_data = unmarshal_json_response(
                errors.ErrUnauthorizedData, http_res
            )
            raise errors.ErrUnauthorized(response_data, http_res)
        if utils.match_response(http_res, "404", "application/json"):
            response_data = unmarshal_json_response(errors.ErrNotFoundData, http_res)
            raise errors.ErrNotFound(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.AlbusDefaultError("Unexpected response received", http_res)
