"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import AsyncBaseSDK, BaseSDK
from albus_sdk import errors, models, operations, utils
from albus_sdk._hooks import HookContext
from albus_sdk.types import BaseModel, OptionalNullable, UNSET
from albus_sdk.utils import get_security_from_env
from albus_sdk.utils.unmarshal_json_response import unmarshal_json_response
from typing import Any, Mapping, Optional, Union, cast


class Invites(BaseSDK):
    def list_invites(
        self,
        *,
        request: Union[
            operations.ListInvitesRequest, operations.ListInvitesRequestTypedDict
        ] = operations.ListInvitesRequest(),
    ) -> models.ListInvitesResponse:
        r"""List pending invitations

        Lists the unexpired invitations into your organization. Requires the admin role.


        If set, this operation will use `bearer_auth` from the global security.

        :param request: The request object to send.
        """
        url_variables = None
        base_url = self._get_url(None, url_variables)

        if not isinstance(request, BaseModel):
            request = utils.unmarshal(request, operations.ListInvitesRequest)
        request = cast(operations.ListInvitesRequest, request)

        req = self._build_request(
            method="GET",
            path="/organization/invites",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            _globals=operations.ListInvitesGlobals(
                x_albus_organization=self.sdk_configuration.globals.x_albus_organization,
            ),
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            allowed_fields=["bearer_auth"],
            timeout_ms=self.sdk_configuration.timeout_ms,
        )

        retry_config = None

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="listInvites",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=["Invites"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=None,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.ListInvitesResponse, http_res)
        if utils.match_response(http_res, "401", "application/json"):
            response_data = unmarshal_json_response(
                errors.ErrUnauthorizedData, http_res
            )
            raise errors.ErrUnauthorized(response_data, http_res)
        if utils.match_response(http_res, "403", "application/json"):
            response_data = unmarshal_json_response(errors.ErrForbiddenData, http_res)
            raise errors.ErrForbidden(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.AlbusDefaultError("Unexpected response received", http_res)

    def create_invite(
        self,
        *,
        email: str,
        role: Optional[models.CreateInviteRequestRole] = "member",
    ) -> models.Invite:
        r"""Invite a user by email

        Invites an email address into your organization. The invitation is redeemed automatically the next time the invitee signs in with that email, and expires after 14 days. Requires the admin role.


        If set, this operation will use `bearer_auth` from the global security.

        :param email: Email address of the person to invite.
        :param role: Role to grant the invitee.
        """
        url_variables = None
        base_url = self._get_url(None, url_variables)

        request = models.CreateInviteRequest(
            email=email,
            role=role,
        )

        req = self._build_request(
            method="POST",
            path="/organization/invites",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            _globals=operations.CreateInviteGlobals(
                x_albus_organization=self.sdk_configuration.globals.x_albus_organization,
            ),
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request, False, False, "json", models.CreateInviteRequest
            ),
            allow_empty_value=None,
            allowed_fields=["bearer_auth"],
            timeout_ms=self.sdk_configuration.timeout_ms,
        )

        retry_config = None

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="createInvite",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=["Invites"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=None,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.Invite, http_res)
        if utils.match_response(http_res, "400", "application/json"):
            response_data = unmarshal_json_response(errors.ErrBadRequestData, http_res)
            raise errors.ErrBadRequest(response_data, http_res)
        if utils.match_response(http_res, "401", "application/json"):
            response_data = unmarshal_json_response(
                errors.ErrUnauthorizedData, http_res
            )
            raise errors.ErrUnauthorized(response_data, http_res)
        if utils.match_response(http_res, "403", "application/json"):
            response_data = unmarshal_json_response(errors.ErrForbiddenData, http_res)
            raise errors.ErrForbidden(response_data, http_res)
        if utils.match_response(http_res, "409", "application/json"):
            response_data = unmarshal_json_response(errors.ErrConflictData, http_res)
            raise errors.ErrConflict(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.AlbusDefaultError("Unexpected response received", http_res)

    def revoke_invite(
        self,
        *,
        id: str,
    ):
        r"""Revoke a pending invitation

        Requires the admin role.

        If set, this operation will use `bearer_auth` from the global security.

        :param id: The invitation identifier.
        """
        url_variables = None
        base_url = self._get_url(None, url_variables)

        request = operations.RevokeInviteRequest(
            id=id,
        )

        req = self._build_request(
            method="DELETE",
            path="/organization/invites/{id}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            _globals=operations.RevokeInviteGlobals(
                x_albus_organization=self.sdk_configuration.globals.x_albus_organization,
            ),
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            allowed_fields=["bearer_auth"],
            timeout_ms=self.sdk_configuration.timeout_ms,
        )

        retry_config = None

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="revokeInvite",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=["Invites"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=None,
        )

        response_data: Any = None
        if utils.match_response(http_res, "204", "*"):
            return
        if utils.match_response(http_res, "401", "application/json"):
            response_data = unmarshal_json_response(
                errors.ErrUnauthorizedData, http_res
            )
            raise errors.ErrUnauthorized(response_data, http_res)
        if utils.match_response(http_res, "403", "application/json"):
            response_data = unmarshal_json_response(errors.ErrForbiddenData, http_res)
            raise errors.ErrForbidden(response_data, http_res)
        if utils.match_response(http_res, "404", "application/json"):
            response_data = unmarshal_json_response(errors.ErrNotFoundData, http_res)
            raise errors.ErrNotFound(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.AlbusDefaultError("Unexpected response received", http_res)


class AsyncInvites(AsyncBaseSDK):
    async def list_invites(
        self,
        *,
        request: Union[
            operations.ListInvitesRequest, operations.ListInvitesRequestTypedDict
        ] = operations.ListInvitesRequest(),
    ) -> models.ListInvitesResponse:
        r"""List pending invitations

        Lists the unexpired invitations into your organization. Requires the admin role.


        If set, this operation will use `bearer_auth` from the global security.

        :param request: The request object to send.
        """
        url_variables = None
        base_url = self._get_url(None, url_variables)

        if not isinstance(request, BaseModel):
            request = utils.unmarshal(request, operations.ListInvitesRequest)
        request = cast(operations.ListInvitesRequest, request)

        req = self._build_request_async(
            method="GET",
            path="/organization/invites",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            _globals=operations.ListInvitesGlobals(
                x_albus_organization=self.sdk_configuration.globals.x_albus_organization,
            ),
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            allowed_fields=["bearer_auth"],
            timeout_ms=self.sdk_configuration.timeout_ms,
        )

        retry_config = None

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="listInvites",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=["Invites"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=None,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.ListInvitesResponse, http_res)
        if utils.match_response(http_res, "401", "application/json"):
            response_data = unmarshal_json_response(
                errors.ErrUnauthorizedData, http_res
            )
            raise errors.ErrUnauthorized(response_data, http_res)
        if utils.match_response(http_res, "403", "application/json"):
            response_data = unmarshal_json_response(errors.ErrForbiddenData, http_res)
            raise errors.ErrForbidden(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.AlbusDefaultError("Unexpected response received", http_res)

    async def create_invite(
        self,
        *,
        email: str,
        role: Optional[models.CreateInviteRequestRole] = "member",
    ) -> models.Invite:
        r"""Invite a user by email

        Invites an email address into your organization. The invitation is redeemed automatically the next time the invitee signs in with that email, and expires after 14 days. Requires the admin role.


        If set, this operation will use `bearer_auth` from the global security.

        :param email: Email address of the person to invite.
        :param role: Role to grant the invitee.
        """
        url_variables = None
        base_url = self._get_url(None, url_variables)

        request = models.CreateInviteRequest(
            email=email,
            role=role,
        )

        req = self._build_request_async(
            method="POST",
            path="/organization/invites",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            _globals=operations.CreateInviteGlobals(
                x_albus_organization=self.sdk_configuration.globals.x_albus_organization,
            ),
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request, False, False, "json", models.CreateInviteRequest
            ),
            allow_empty_value=None,
            allowed_fields=["bearer_auth"],
            timeout_ms=self.sdk_configuration.timeout_ms,
        )

        retry_config = None

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="createInvite",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=["Invites"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=None,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.Invite, http_res)
        if utils.match_response(http_res, "400", "application/json"):
            response_data = unmarshal_json_response(errors.ErrBadRequestData, http_res)
            raise errors.ErrBadRequest(response_data, http_res)
        if utils.match_response(http_res, "401", "application/json"):
            response_data = unmarshal_json_response(
                errors.ErrUnauthorizedData, http_res
            )
            raise errors.ErrUnauthorized(response_data, http_res)
        if utils.match_response(http_res, "403", "application/json"):
            response_data = unmarshal_json_response(errors.ErrForbiddenData, http_res)
            raise errors.ErrForbidden(response_data, http_res)
        if utils.match_response(http_res, "409", "application/json"):
            response_data = unmarshal_json_response(errors.ErrConflictData, http_res)
            raise errors.ErrConflict(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.AlbusDefaultError("Unexpected response received", http_res)

    async def revoke_invite(
        self,
        *,
        id: str,
    ):
        r"""Revoke a pending invitation

        Requires the admin role.

        If set, this operation will use `bearer_auth` from the global security.

        :param id: The invitation identifier.
        """
        url_variables = None
        base_url = self._get_url(None, url_variables)

        request = operations.RevokeInviteRequest(
            id=id,
        )

        req = self._build_request_async(
            method="DELETE",
            path="/organization/invites/{id}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            _globals=operations.RevokeInviteGlobals(
                x_albus_organization=self.sdk_configuration.globals.x_albus_organization,
            ),
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            allowed_fields=["bearer_auth"],
            timeout_ms=self.sdk_configuration.timeout_ms,
        )

        retry_config = None

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="revokeInvite",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=["Invites"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=None,
        )

        response_data: Any = None
        if utils.match_response(http_res, "204", "*"):
            return
        if utils.match_response(http_res, "401", "application/json"):
            response_data = unmarshal_json_response(
                errors.ErrUnauthorizedData, http_res
            )
            raise errors.ErrUnauthorized(response_data, http_res)
        if utils.match_response(http_res, "403", "application/json"):
            response_data = unmarshal_json_response(errors.ErrForbiddenData, http_res)
            raise errors.ErrForbidden(response_data, http_res)
        if utils.match_response(http_res, "404", "application/json"):
            response_data = unmarshal_json_response(errors.ErrNotFoundData, http_res)
            raise errors.ErrNotFound(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.AlbusDefaultError("Unexpected response received", http_res)
