"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import AsyncBaseSDK, BaseSDK
from .httpclient import (
    AsyncHttpClient,
    ClientOwner,
    HttpClient,
    close_clients,
    close_clients_async,
)
from .sdkconfiguration import SDKConfiguration
from .utils.logger import Logger, get_default_logger
from .utils.retries import RetryConfig
from albus_sdk import models as models_, utils
from albus_sdk._hooks import SDKHooks
from albus_sdk.types import OptionalNullable, UNSET
import httpx
import importlib
import sys
from typing import Dict, Optional, TYPE_CHECKING, cast
import weakref

if TYPE_CHECKING:
    from albus_sdk.agents import Agents, AsyncAgents
    from albus_sdk.auth import AsyncAuth, Auth
    from albus_sdk.health import AsyncHealth, Health
    from albus_sdk.invites import AsyncInvites, Invites
    from albus_sdk.models_ import AsyncModels, Models
    from albus_sdk.secrets import AsyncSecrets, Secrets
    from albus_sdk.sessions import AsyncSessions, Sessions
    from albus_sdk.tokens import AsyncTokens, Tokens


class Albus(BaseSDK):
    r"""Albus API: Albus service REST API"""

    secrets: "Secrets"
    r"""Manage secrets available to agent sessions."""
    sessions: "Sessions"
    r"""Run and inspect agent sessions."""
    tokens: "Tokens"
    r"""Manage organization API keys."""
    agents: "Agents"
    r"""Inspect the agents that have run in your organization."""
    models: "Models"
    r"""Discover the models available to run agents on."""
    health: "Health"
    r"""Check service availability."""
    auth: "Auth"
    r"""Identify the authenticated user."""
    invites: "Invites"
    _sub_sdk_map = {
        "secrets": ("albus_sdk.secrets", "Secrets"),
        "sessions": ("albus_sdk.sessions", "Sessions"),
        "tokens": ("albus_sdk.tokens", "Tokens"),
        "agents": ("albus_sdk.agents", "Agents"),
        "models": ("albus_sdk.models_", "Models"),
        "health": ("albus_sdk.health", "Health"),
        "auth": ("albus_sdk.auth", "Auth"),
        "invites": ("albus_sdk.invites", "Invites"),
    }

    def __init__(
        self,
        api_key: Optional[str] = None,
        access_token: Optional[str] = None,
        server_idx: Optional[int] = None,
        url_params: Optional[Dict[str, str]] = None,
        server_url: Optional[str] = None,
        client: Optional[HttpClient] = None,
        retry_config: OptionalNullable[RetryConfig] = UNSET,
        timeout_ms: Optional[int] = None,
        debug_logger: Optional[Logger] = None,
    ) -> None:
        r"""Instantiates the SDK configuring it with the provided parameters.

        :param server_idx: The index of the server to use for all methods
        :param server_url: The server URL to use for all methods
        :param url_params: Parameters to optionally template the server URL with
        :param client: The HTTP client to use for all synchronous methods
        :param retry_config: The retry configuration to use for all supported methods
        :param timeout_ms: Optional request timeout applied to each operation in milliseconds
        """
        if api_key is not None and access_token is not None:
            raise ValueError("api_key and access_token cannot both be set")

        security = None
        if api_key is not None:
            security = models_.Security(api_key_auth=api_key)
        elif access_token is not None:
            security = models_.Security(bearer_auth=access_token)

        client_supplied = True
        if client is None:
            client = httpx.Client(follow_redirects=True)
            client_supplied = False

        assert issubclass(
            type(client), HttpClient
        ), "The provided client must implement the HttpClient protocol."

        if debug_logger is None:
            debug_logger = get_default_logger()

        if server_url is not None:
            if url_params is not None:
                server_url = utils.template_url(server_url, url_params)

        BaseSDK.__init__(
            self,
            SDKConfiguration(
                client=client,
                client_supplied=client_supplied,
                async_client=None,
                async_client_supplied=False,
                security=security,
                server_url=server_url,
                server_idx=server_idx,
                retry_config=retry_config,
                timeout_ms=timeout_ms,
                debug_logger=debug_logger,
            ),
            parent_ref=self,
        )

        hooks = SDKHooks()

        # pylint: disable=protected-access
        self.sdk_configuration.__dict__["_hooks"] = hooks

        self.sdk_configuration = hooks.sdk_init(self.sdk_configuration)

        weakref.finalize(
            self,
            close_clients,
            cast(ClientOwner, self.sdk_configuration),
            self.sdk_configuration.client,
            self.sdk_configuration.client_supplied,
        )

    def dynamic_import(self, modname, retries=3):
        for attempt in range(retries):
            try:
                return importlib.import_module(modname)
            except KeyError:
                # Clear any half-initialized module and retry
                sys.modules.pop(modname, None)
                if attempt == retries - 1:
                    break
        raise KeyError(f"Failed to import module '{modname}' after {retries} attempts")

    def __getattr__(self, name: str):
        if name in self._sub_sdk_map:
            module_path, class_name = self._sub_sdk_map[name]
            try:
                module = self.dynamic_import(module_path)
                klass = getattr(module, class_name)
                instance = klass(self.sdk_configuration, parent_ref=self)
                setattr(self, name, instance)
                return instance
            except ImportError as e:
                raise AttributeError(
                    f"Failed to import module {module_path} for attribute {name}: {e}"
                ) from e
            except AttributeError as e:
                raise AttributeError(
                    f"Failed to find class {class_name} in module {module_path} for attribute {name}: {e}"
                ) from e

        raise AttributeError(
            f"'{type(self).__name__}' object has no attribute '{name}'"
        )

    def __dir__(self):
        default_attrs = list(super().__dir__())
        lazy_attrs = list(self._sub_sdk_map.keys())
        return sorted(list(set(default_attrs + lazy_attrs)))

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        if (
            self.sdk_configuration.client is not None
            and not self.sdk_configuration.client_supplied
        ):
            self.sdk_configuration.client.close()
        self.sdk_configuration.client = None


class AsyncAlbus(AsyncBaseSDK):
    r"""Albus API: Albus service REST API"""

    secrets: "AsyncSecrets"
    r"""Manage secrets available to agent sessions."""
    sessions: "AsyncSessions"
    r"""Run and inspect agent sessions."""
    tokens: "AsyncTokens"
    r"""Manage organization API keys."""
    agents: "AsyncAgents"
    r"""Inspect the agents that have run in your organization."""
    models: "AsyncModels"
    r"""Discover the models available to run agents on."""
    health: "AsyncHealth"
    r"""Check service availability."""
    auth: "AsyncAuth"
    r"""Identify the authenticated user."""
    invites: "AsyncInvites"
    _sub_sdk_map = {
        "secrets": ("albus_sdk.secrets", "AsyncSecrets"),
        "sessions": ("albus_sdk.sessions", "AsyncSessions"),
        "tokens": ("albus_sdk.tokens", "AsyncTokens"),
        "agents": ("albus_sdk.agents", "AsyncAgents"),
        "models": ("albus_sdk.models_", "AsyncModels"),
        "health": ("albus_sdk.health", "AsyncHealth"),
        "auth": ("albus_sdk.auth", "AsyncAuth"),
        "invites": ("albus_sdk.invites", "AsyncInvites"),
    }

    def __init__(
        self,
        api_key: Optional[str] = None,
        access_token: Optional[str] = None,
        server_idx: Optional[int] = None,
        url_params: Optional[Dict[str, str]] = None,
        server_url: Optional[str] = None,
        async_client: Optional[AsyncHttpClient] = None,
        retry_config: OptionalNullable[RetryConfig] = UNSET,
        timeout_ms: Optional[int] = None,
        debug_logger: Optional[Logger] = None,
    ) -> None:
        r"""Instantiates the SDK configuring it with the provided parameters.

        :param server_idx: The index of the server to use for all methods
        :param server_url: The server URL to use for all methods
        :param url_params: Parameters to optionally template the server URL with
        :param async_client: The Async HTTP client to use for all asynchronous methods
        :param retry_config: The retry configuration to use for all supported methods
        :param timeout_ms: Optional request timeout applied to each operation in milliseconds
        """
        if api_key is not None and access_token is not None:
            raise ValueError("api_key and access_token cannot both be set")

        security = None
        if api_key is not None:
            security = models_.Security(api_key_auth=api_key)
        elif access_token is not None:
            security = models_.Security(bearer_auth=access_token)

        async_client_supplied = True
        if async_client is None:
            async_client = httpx.AsyncClient(follow_redirects=True)
            async_client_supplied = False
        if debug_logger is None:
            debug_logger = get_default_logger()
        assert issubclass(
            type(async_client), AsyncHttpClient
        ), "The provided async_client must implement the AsyncHttpClient protocol."

        if server_url is not None:
            if url_params is not None:
                server_url = utils.template_url(server_url, url_params)

        AsyncBaseSDK.__init__(
            self,
            SDKConfiguration(
                client=None,
                client_supplied=False,
                async_client=async_client,
                async_client_supplied=async_client_supplied,
                security=security,
                server_url=server_url,
                server_idx=server_idx,
                retry_config=retry_config,
                timeout_ms=timeout_ms,
                debug_logger=debug_logger,
            ),
            parent_ref=self,
        )

        hooks = SDKHooks()

        # pylint: disable=protected-access
        self.sdk_configuration.__dict__["_hooks"] = hooks

        self.sdk_configuration = hooks.sdk_init(self.sdk_configuration)

        weakref.finalize(
            self,
            close_clients_async,
            cast(ClientOwner, self.sdk_configuration),
            self.sdk_configuration.async_client,
            self.sdk_configuration.async_client_supplied,
        )

    def dynamic_import(self, modname, retries=3):
        for attempt in range(retries):
            try:
                return importlib.import_module(modname)
            except KeyError:
                # Clear any half-initialized module and retry
                sys.modules.pop(modname, None)
                if attempt == retries - 1:
                    break
        raise KeyError(f"Failed to import module '{modname}' after {retries} attempts")

    def __getattr__(self, name: str):
        if name in self._sub_sdk_map:
            module_path, class_name = self._sub_sdk_map[name]
            try:
                module = self.dynamic_import(module_path)
                klass = getattr(module, class_name)
                instance = klass(self.sdk_configuration, parent_ref=self)
                setattr(self, name, instance)
                return instance
            except ImportError as e:
                raise AttributeError(
                    f"Failed to import module {module_path} for attribute {name}: {e}"
                ) from e
            except AttributeError as e:
                raise AttributeError(
                    f"Failed to find class {class_name} in module {module_path} for attribute {name}: {e}"
                ) from e

        raise AttributeError(
            f"'{type(self).__name__}' object has no attribute '{name}'"
        )

    def __dir__(self):
        default_attrs = list(super().__dir__())
        lazy_attrs = list(self._sub_sdk_map.keys())
        return sorted(list(set(default_attrs + lazy_attrs)))

    async def __aenter__(self):
        return self

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        if (
            self.sdk_configuration.async_client is not None
            and not self.sdk_configuration.async_client_supplied
        ):
            await self.sdk_configuration.async_client.aclose()
        self.sdk_configuration.async_client = None
