"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import AsyncBaseSDK, BaseSDK
from albus_sdk import errors, models, operations, utils
from albus_sdk._hooks import HookContext
from albus_sdk.types import OptionalNullable, UNSET
from albus_sdk.utils import get_security_from_env
from albus_sdk.utils.unmarshal_json_response import unmarshal_json_response
from typing import Any, Optional, Union


class Sessions(BaseSDK):
    r"""Run and inspect agent sessions."""

    def list_sessions(
        self,
    ) -> models.ListSessionsResponse:
        r"""List all sessions

        If set, this operation will use either `bearer_auth` or `api_key` from the global security.

        """
        url_variables = None
        base_url = self._get_url(None, url_variables)
        req = self._build_request(
            method="GET",
            path="/sessions",
            base_url=base_url,
            url_variables=url_variables,
            request=None,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            allowed_fields=["bearer_auth", "api_key"],
            timeout_ms=self.sdk_configuration.timeout_ms,
        )

        retry_config = None

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="listSessions",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=["Sessions"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=None,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.ListSessionsResponse, http_res)
        if utils.match_response(http_res, "401", "application/json"):
            response_data = unmarshal_json_response(
                errors.ErrUnauthorizedData, http_res
            )
            raise errors.ErrUnauthorized(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.AlbusDefaultError("Unexpected response received", http_res)

    def get_session(
        self,
        *,
        id: str,
        after: Optional[str] = None,
        limit: Optional[int] = 100,
    ) -> models.SessionResponse:
        r"""Get a session with its messages

        Returns the session's metadata and a page of its messages ordered by cursor ascending. Use `after` and `limit` to page through messages.


        If set, this operation will use either `bearer_auth` or `api_key` from the global security.

        :param id: Client-provided session identifier. Use the same value across requests to continue the same agent session.
        :param after: Opaque pagination cursor. Return only items positioned after it; pass a value obtained from a previous page to fetch the next one.

        :param limit: Maximum number of items to return.
        """
        url_variables = None
        base_url = self._get_url(None, url_variables)

        request = operations.GetSessionRequest(
            id=id,
            after=after,
            limit=limit,
        )

        req = self._build_request(
            method="GET",
            path="/sessions/{id}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            allowed_fields=["bearer_auth", "api_key"],
            timeout_ms=self.sdk_configuration.timeout_ms,
        )

        retry_config = None

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="getSession",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=["Sessions"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=None,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.SessionResponse, http_res)
        if utils.match_response(http_res, "400", "application/json"):
            response_data = unmarshal_json_response(errors.ErrBadRequestData, http_res)
            raise errors.ErrBadRequest(response_data, http_res)
        if utils.match_response(http_res, "401", "application/json"):
            response_data = unmarshal_json_response(
                errors.ErrUnauthorizedData, http_res
            )
            raise errors.ErrUnauthorized(response_data, http_res)
        if utils.match_response(http_res, "404", "application/json"):
            response_data = unmarshal_json_response(errors.ErrNotFoundData, http_res)
            raise errors.ErrNotFound(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.AlbusDefaultError("Unexpected response received", http_res)

    def run_session(
        self,
        *,
        id: str,
        user_prompt: str,
        agent_name: str,
        agent: Union[models.AgentConfig, models.AgentConfigTypedDict],
        invocation_key: Optional[str] = None,
        wait_timeout_seconds: Optional[int] = 1800,
        retry_config: OptionalNullable[utils.RetryConfig] = UNSET,
    ) -> operations.RunSessionResponse:
        r"""Run or resume a session

        Runs the session with the given ID, creating it if it does not exist and resuming it otherwise. Each call is a single invocation, optionally named by the Idempotency-Key header, whose value is the invocation's key. Supplying a key makes the call safe to retry: retrying with the same key and an identical body re-attaches to the in-flight invocation and returns its current state; a differing body for the same key returns 409; a new key while another invocation is still running returns 423. Omitting the header starts a fresh, non-idempotent invocation each time; the server generates a key and returns it in the Idempotency-Key response header.

        With `wait_timeout_seconds` the request long-polls: it blocks until the invocation's assistant response is available and returns it in `message`. Omit it to wait up to 30 minutes, or pass 0 to return as soon as the invocation is accepted. A positive value bounds the wait in seconds; if it elapses first the request fails with 504 and a JSON body, letting the client distinguish an expected server-side timeout from a transport error; the client may retry.


        If set, this operation will use either `bearer_auth` or `api_key` from the global security.

        :param id: Client-provided session identifier. Use the same value across requests to continue the same agent session.
        :param user_prompt: The user prompt driving this invocation.
        :param agent_name: Human-readable name identifying the agent (e.g. \"support-triage\"). Invocations sharing a name are grouped as one agent; each distinct configuration under it becomes a revision.

        :param agent: The agent configuration for an invocation: the model, tools, instructions, and MCP servers that define its behavior. Invocations with the same configuration share a revision.

        :param invocation_key: Optional but strongly encouraged. The key naming this invocation of the session, unique within your organization: reuse the same value to safely retry a request, read the invocation back with `GET /traces/{invocation_key}`, and use a new value to start a new invocation. When omitted, the server generates a key for the invocation and returns it in the Idempotency-Key response header, but the request is not retry-safe.

        :param wait_timeout_seconds: Wait up to this many seconds for the assistant response. Omit to wait up to 30 minutes; use 0 to return after the invocation is accepted.

        :param retry_config: Override the SDK retry configuration for this invocation.
        """
        url_variables = None
        base_url = self._get_url(None, url_variables)
        timeout_ms = self.sdk_configuration.timeout_ms

        if timeout_ms is None:
            timeout_ms = 1860000

        request = operations.RunSessionRequest(
            id=id,
            invocation_key=invocation_key,
            wait_timeout_seconds=wait_timeout_seconds,
            body=models.RunSessionRequest(
                user_prompt=user_prompt,
                agent_name=agent_name,
                agent=utils.get_pydantic_model(agent, models.AgentConfig),
            ),
        )

        req = self._build_request(
            method="POST",
            path="/sessions/{id}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body, False, False, "json", models.RunSessionRequest
            ),
            allow_empty_value=None,
            allowed_fields=["bearer_auth", "api_key"],
            timeout_ms=timeout_ms,
        )

        retries = retry_config

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        request_retry_config = None
        if isinstance(retries, utils.RetryConfig):
            request_retry_config = (
                retries,
                ["429", "500", "502", "503", "504"],
            )

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="runSession",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=["Sessions"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=request_retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return operations.RunSessionResponse(
                result=unmarshal_json_response(models.RunSessionResponse, http_res),
                headers=utils.get_response_headers(http_res.headers),
            )
        if utils.match_response(http_res, "400", "application/json"):
            response_data = unmarshal_json_response(errors.ErrBadRequestData, http_res)
            raise errors.ErrBadRequest(response_data, http_res)
        if utils.match_response(http_res, "401", "application/json"):
            response_data = unmarshal_json_response(
                errors.ErrUnauthorizedData, http_res
            )
            raise errors.ErrUnauthorized(response_data, http_res)
        if utils.match_response(http_res, "402", "application/json"):
            response_data = unmarshal_json_response(
                errors.ErrInsufficientCreditData, http_res
            )
            raise errors.ErrInsufficientCredit(response_data, http_res)
        if utils.match_response(http_res, "409", "application/json"):
            response_data = unmarshal_json_response(errors.ErrConflictData, http_res)
            raise errors.ErrConflict(response_data, http_res)
        if utils.match_response(http_res, "410", "application/json"):
            response_data = unmarshal_json_response(
                errors.ErrInvocationCanceledData, http_res
            )
            raise errors.ErrInvocationCanceled(response_data, http_res)
        if utils.match_response(http_res, "423", "application/json"):
            response_data = unmarshal_json_response(errors.ErrLockedData, http_res)
            raise errors.ErrLocked(response_data, http_res)
        if utils.match_response(http_res, "429", "application/json"):
            response_data = unmarshal_json_response(
                errors.ErrQuotaExceededData, http_res
            )
            raise errors.ErrQuotaExceeded(response_data, http_res)
        if utils.match_response(http_res, "502", "application/json"):
            response_data = unmarshal_json_response(
                errors.ErrInvocationFailedData, http_res
            )
            raise errors.ErrInvocationFailed(response_data, http_res)
        if utils.match_response(http_res, "504", "application/json"):
            response_data = unmarshal_json_response(errors.ErrTimeoutData, http_res)
            raise errors.ErrTimeout(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.AlbusDefaultError("Unexpected response received", http_res)

    def delete_session(
        self,
        *,
        id: str,
    ):
        r"""Delete a session

        If set, this operation will use either `bearer_auth` or `api_key` from the global security.

        :param id: Client-provided session identifier. Use the same value across requests to continue the same agent session.
        """
        url_variables = None
        base_url = self._get_url(None, url_variables)

        request = operations.DeleteSessionRequest(
            id=id,
        )

        req = self._build_request(
            method="DELETE",
            path="/sessions/{id}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            allowed_fields=["bearer_auth", "api_key"],
            timeout_ms=self.sdk_configuration.timeout_ms,
        )

        retry_config = None

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="deleteSession",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=["Sessions"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=None,
        )

        response_data: Any = None
        if utils.match_response(http_res, "204", "*"):
            return
        if utils.match_response(http_res, "401", "application/json"):
            response_data = unmarshal_json_response(
                errors.ErrUnauthorizedData, http_res
            )
            raise errors.ErrUnauthorized(response_data, http_res)
        if utils.match_response(http_res, "404", "application/json"):
            response_data = unmarshal_json_response(errors.ErrNotFoundData, http_res)
            raise errors.ErrNotFound(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.AlbusDefaultError("Unexpected response received", http_res)

    def cancel_session(
        self,
        *,
        id: str,
    ) -> models.CancelSessionResponse:
        r"""Cancel a session's running invocation

        Requests cancellation of the invocation currently running for the session. Cancellation is asynchronous: the call returns once the request is accepted, and the invocation resolves as canceled shortly after, unlocking the session for new invocations. A request waiting on the invocation receives its terminal outcome. Returns 409 when the session has no invocation running.


        If set, this operation will use either `bearer_auth` or `api_key` from the global security.

        :param id: Client-provided session identifier. Use the same value across requests to continue the same agent session.
        """
        url_variables = None
        base_url = self._get_url(None, url_variables)

        request = operations.CancelSessionRequest(
            id=id,
        )

        req = self._build_request(
            method="POST",
            path="/sessions/{id}/cancel",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            allowed_fields=["bearer_auth", "api_key"],
            timeout_ms=self.sdk_configuration.timeout_ms,
        )

        retry_config = None

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="cancelSession",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=["Sessions"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=None,
        )

        response_data: Any = None
        if utils.match_response(http_res, "202", "application/json"):
            return unmarshal_json_response(models.CancelSessionResponse, http_res)
        if utils.match_response(http_res, "401", "application/json"):
            response_data = unmarshal_json_response(
                errors.ErrUnauthorizedData, http_res
            )
            raise errors.ErrUnauthorized(response_data, http_res)
        if utils.match_response(http_res, "404", "application/json"):
            response_data = unmarshal_json_response(errors.ErrNotFoundData, http_res)
            raise errors.ErrNotFound(response_data, http_res)
        if utils.match_response(http_res, "409", "application/json"):
            response_data = unmarshal_json_response(errors.ErrConflictData, http_res)
            raise errors.ErrConflict(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.AlbusDefaultError("Unexpected response received", http_res)

    def get_session_audit(
        self,
        *,
        id: str,
        after: Optional[str] = None,
        limit: Optional[int] = 100,
    ) -> models.ListAuditEventsResponse:
        r"""List a session's audit log

        Returns the session's audit log — an immutable, time-ordered record of what happened during its invocations (LLM calls, tool results, and invocation outcomes). Events are ordered by the time they occurred. Use `after` and `limit` to page through them; pass the response's `next_cursor` as the next request's `after` to fetch the following page.


        If set, this operation will use either `bearer_auth` or `api_key` from the global security.

        :param id: Client-provided session identifier. Use the same value across requests to continue the same agent session.
        :param after: Opaque pagination cursor. Return only items positioned after it; pass a value obtained from a previous page to fetch the next one.

        :param limit: Maximum number of items to return.
        """
        url_variables = None
        base_url = self._get_url(None, url_variables)

        request = operations.GetSessionAuditRequest(
            id=id,
            after=after,
            limit=limit,
        )

        req = self._build_request(
            method="GET",
            path="/sessions/{id}/audit",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            allowed_fields=["bearer_auth", "api_key"],
            timeout_ms=self.sdk_configuration.timeout_ms,
        )

        retry_config = None

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="getSessionAudit",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=["Sessions"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=None,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.ListAuditEventsResponse, http_res)
        if utils.match_response(http_res, "400", "application/json"):
            response_data = unmarshal_json_response(errors.ErrBadRequestData, http_res)
            raise errors.ErrBadRequest(response_data, http_res)
        if utils.match_response(http_res, "401", "application/json"):
            response_data = unmarshal_json_response(
                errors.ErrUnauthorizedData, http_res
            )
            raise errors.ErrUnauthorized(response_data, http_res)
        if utils.match_response(http_res, "404", "application/json"):
            response_data = unmarshal_json_response(errors.ErrNotFoundData, http_res)
            raise errors.ErrNotFound(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.AlbusDefaultError("Unexpected response received", http_res)


class AsyncSessions(AsyncBaseSDK):
    r"""Run and inspect agent sessions."""

    async def list_sessions(
        self,
    ) -> models.ListSessionsResponse:
        r"""List all sessions

        If set, this operation will use either `bearer_auth` or `api_key` from the global security.

        """
        url_variables = None
        base_url = self._get_url(None, url_variables)
        req = self._build_request_async(
            method="GET",
            path="/sessions",
            base_url=base_url,
            url_variables=url_variables,
            request=None,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            allowed_fields=["bearer_auth", "api_key"],
            timeout_ms=self.sdk_configuration.timeout_ms,
        )

        retry_config = None

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="listSessions",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=["Sessions"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=None,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.ListSessionsResponse, http_res)
        if utils.match_response(http_res, "401", "application/json"):
            response_data = unmarshal_json_response(
                errors.ErrUnauthorizedData, http_res
            )
            raise errors.ErrUnauthorized(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.AlbusDefaultError("Unexpected response received", http_res)

    async def get_session(
        self,
        *,
        id: str,
        after: Optional[str] = None,
        limit: Optional[int] = 100,
    ) -> models.SessionResponse:
        r"""Get a session with its messages

        Returns the session's metadata and a page of its messages ordered by cursor ascending. Use `after` and `limit` to page through messages.


        If set, this operation will use either `bearer_auth` or `api_key` from the global security.

        :param id: Client-provided session identifier. Use the same value across requests to continue the same agent session.
        :param after: Opaque pagination cursor. Return only items positioned after it; pass a value obtained from a previous page to fetch the next one.

        :param limit: Maximum number of items to return.
        """
        url_variables = None
        base_url = self._get_url(None, url_variables)

        request = operations.GetSessionRequest(
            id=id,
            after=after,
            limit=limit,
        )

        req = self._build_request_async(
            method="GET",
            path="/sessions/{id}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            allowed_fields=["bearer_auth", "api_key"],
            timeout_ms=self.sdk_configuration.timeout_ms,
        )

        retry_config = None

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="getSession",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=["Sessions"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=None,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.SessionResponse, http_res)
        if utils.match_response(http_res, "400", "application/json"):
            response_data = unmarshal_json_response(errors.ErrBadRequestData, http_res)
            raise errors.ErrBadRequest(response_data, http_res)
        if utils.match_response(http_res, "401", "application/json"):
            response_data = unmarshal_json_response(
                errors.ErrUnauthorizedData, http_res
            )
            raise errors.ErrUnauthorized(response_data, http_res)
        if utils.match_response(http_res, "404", "application/json"):
            response_data = unmarshal_json_response(errors.ErrNotFoundData, http_res)
            raise errors.ErrNotFound(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.AlbusDefaultError("Unexpected response received", http_res)

    async def run_session(
        self,
        *,
        id: str,
        user_prompt: str,
        agent_name: str,
        agent: Union[models.AgentConfig, models.AgentConfigTypedDict],
        invocation_key: Optional[str] = None,
        wait_timeout_seconds: Optional[int] = 1800,
        retry_config: OptionalNullable[utils.RetryConfig] = UNSET,
    ) -> operations.RunSessionResponse:
        r"""Run or resume a session

        Runs the session with the given ID, creating it if it does not exist and resuming it otherwise. Each call is a single invocation, optionally named by the Idempotency-Key header, whose value is the invocation's key. Supplying a key makes the call safe to retry: retrying with the same key and an identical body re-attaches to the in-flight invocation and returns its current state; a differing body for the same key returns 409; a new key while another invocation is still running returns 423. Omitting the header starts a fresh, non-idempotent invocation each time; the server generates a key and returns it in the Idempotency-Key response header.

        With `wait_timeout_seconds` the request long-polls: it blocks until the invocation's assistant response is available and returns it in `message`. Omit it to wait up to 30 minutes, or pass 0 to return as soon as the invocation is accepted. A positive value bounds the wait in seconds; if it elapses first the request fails with 504 and a JSON body, letting the client distinguish an expected server-side timeout from a transport error; the client may retry.


        If set, this operation will use either `bearer_auth` or `api_key` from the global security.

        :param id: Client-provided session identifier. Use the same value across requests to continue the same agent session.
        :param user_prompt: The user prompt driving this invocation.
        :param agent_name: Human-readable name identifying the agent (e.g. \"support-triage\"). Invocations sharing a name are grouped as one agent; each distinct configuration under it becomes a revision.

        :param agent: The agent configuration for an invocation: the model, tools, instructions, and MCP servers that define its behavior. Invocations with the same configuration share a revision.

        :param invocation_key: Optional but strongly encouraged. The key naming this invocation of the session, unique within your organization: reuse the same value to safely retry a request, read the invocation back with `GET /traces/{invocation_key}`, and use a new value to start a new invocation. When omitted, the server generates a key for the invocation and returns it in the Idempotency-Key response header, but the request is not retry-safe.

        :param wait_timeout_seconds: Wait up to this many seconds for the assistant response. Omit to wait up to 30 minutes; use 0 to return after the invocation is accepted.

        :param retry_config: Override the SDK retry configuration for this invocation.
        """
        url_variables = None
        base_url = self._get_url(None, url_variables)
        timeout_ms = self.sdk_configuration.timeout_ms

        if timeout_ms is None:
            timeout_ms = 1860000

        request = operations.RunSessionRequest(
            id=id,
            invocation_key=invocation_key,
            wait_timeout_seconds=wait_timeout_seconds,
            body=models.RunSessionRequest(
                user_prompt=user_prompt,
                agent_name=agent_name,
                agent=utils.get_pydantic_model(agent, models.AgentConfig),
            ),
        )

        req = self._build_request_async(
            method="POST",
            path="/sessions/{id}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body, False, False, "json", models.RunSessionRequest
            ),
            allow_empty_value=None,
            allowed_fields=["bearer_auth", "api_key"],
            timeout_ms=timeout_ms,
        )

        retries = retry_config

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        request_retry_config = None
        if isinstance(retries, utils.RetryConfig):
            request_retry_config = (
                retries,
                ["429", "500", "502", "503", "504"],
            )

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="runSession",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=["Sessions"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=request_retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return operations.RunSessionResponse(
                result=unmarshal_json_response(models.RunSessionResponse, http_res),
                headers=utils.get_response_headers(http_res.headers),
            )
        if utils.match_response(http_res, "400", "application/json"):
            response_data = unmarshal_json_response(errors.ErrBadRequestData, http_res)
            raise errors.ErrBadRequest(response_data, http_res)
        if utils.match_response(http_res, "401", "application/json"):
            response_data = unmarshal_json_response(
                errors.ErrUnauthorizedData, http_res
            )
            raise errors.ErrUnauthorized(response_data, http_res)
        if utils.match_response(http_res, "402", "application/json"):
            response_data = unmarshal_json_response(
                errors.ErrInsufficientCreditData, http_res
            )
            raise errors.ErrInsufficientCredit(response_data, http_res)
        if utils.match_response(http_res, "409", "application/json"):
            response_data = unmarshal_json_response(errors.ErrConflictData, http_res)
            raise errors.ErrConflict(response_data, http_res)
        if utils.match_response(http_res, "410", "application/json"):
            response_data = unmarshal_json_response(
                errors.ErrInvocationCanceledData, http_res
            )
            raise errors.ErrInvocationCanceled(response_data, http_res)
        if utils.match_response(http_res, "423", "application/json"):
            response_data = unmarshal_json_response(errors.ErrLockedData, http_res)
            raise errors.ErrLocked(response_data, http_res)
        if utils.match_response(http_res, "429", "application/json"):
            response_data = unmarshal_json_response(
                errors.ErrQuotaExceededData, http_res
            )
            raise errors.ErrQuotaExceeded(response_data, http_res)
        if utils.match_response(http_res, "502", "application/json"):
            response_data = unmarshal_json_response(
                errors.ErrInvocationFailedData, http_res
            )
            raise errors.ErrInvocationFailed(response_data, http_res)
        if utils.match_response(http_res, "504", "application/json"):
            response_data = unmarshal_json_response(errors.ErrTimeoutData, http_res)
            raise errors.ErrTimeout(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.AlbusDefaultError("Unexpected response received", http_res)

    async def delete_session(
        self,
        *,
        id: str,
    ):
        r"""Delete a session

        If set, this operation will use either `bearer_auth` or `api_key` from the global security.

        :param id: Client-provided session identifier. Use the same value across requests to continue the same agent session.
        """
        url_variables = None
        base_url = self._get_url(None, url_variables)

        request = operations.DeleteSessionRequest(
            id=id,
        )

        req = self._build_request_async(
            method="DELETE",
            path="/sessions/{id}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            allowed_fields=["bearer_auth", "api_key"],
            timeout_ms=self.sdk_configuration.timeout_ms,
        )

        retry_config = None

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="deleteSession",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=["Sessions"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=None,
        )

        response_data: Any = None
        if utils.match_response(http_res, "204", "*"):
            return
        if utils.match_response(http_res, "401", "application/json"):
            response_data = unmarshal_json_response(
                errors.ErrUnauthorizedData, http_res
            )
            raise errors.ErrUnauthorized(response_data, http_res)
        if utils.match_response(http_res, "404", "application/json"):
            response_data = unmarshal_json_response(errors.ErrNotFoundData, http_res)
            raise errors.ErrNotFound(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.AlbusDefaultError("Unexpected response received", http_res)

    async def cancel_session(
        self,
        *,
        id: str,
    ) -> models.CancelSessionResponse:
        r"""Cancel a session's running invocation

        Requests cancellation of the invocation currently running for the session. Cancellation is asynchronous: the call returns once the request is accepted, and the invocation resolves as canceled shortly after, unlocking the session for new invocations. A request waiting on the invocation receives its terminal outcome. Returns 409 when the session has no invocation running.


        If set, this operation will use either `bearer_auth` or `api_key` from the global security.

        :param id: Client-provided session identifier. Use the same value across requests to continue the same agent session.
        """
        url_variables = None
        base_url = self._get_url(None, url_variables)

        request = operations.CancelSessionRequest(
            id=id,
        )

        req = self._build_request_async(
            method="POST",
            path="/sessions/{id}/cancel",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            allowed_fields=["bearer_auth", "api_key"],
            timeout_ms=self.sdk_configuration.timeout_ms,
        )

        retry_config = None

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="cancelSession",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=["Sessions"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=None,
        )

        response_data: Any = None
        if utils.match_response(http_res, "202", "application/json"):
            return unmarshal_json_response(models.CancelSessionResponse, http_res)
        if utils.match_response(http_res, "401", "application/json"):
            response_data = unmarshal_json_response(
                errors.ErrUnauthorizedData, http_res
            )
            raise errors.ErrUnauthorized(response_data, http_res)
        if utils.match_response(http_res, "404", "application/json"):
            response_data = unmarshal_json_response(errors.ErrNotFoundData, http_res)
            raise errors.ErrNotFound(response_data, http_res)
        if utils.match_response(http_res, "409", "application/json"):
            response_data = unmarshal_json_response(errors.ErrConflictData, http_res)
            raise errors.ErrConflict(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.AlbusDefaultError("Unexpected response received", http_res)

    async def get_session_audit(
        self,
        *,
        id: str,
        after: Optional[str] = None,
        limit: Optional[int] = 100,
    ) -> models.ListAuditEventsResponse:
        r"""List a session's audit log

        Returns the session's audit log — an immutable, time-ordered record of what happened during its invocations (LLM calls, tool results, and invocation outcomes). Events are ordered by the time they occurred. Use `after` and `limit` to page through them; pass the response's `next_cursor` as the next request's `after` to fetch the following page.


        If set, this operation will use either `bearer_auth` or `api_key` from the global security.

        :param id: Client-provided session identifier. Use the same value across requests to continue the same agent session.
        :param after: Opaque pagination cursor. Return only items positioned after it; pass a value obtained from a previous page to fetch the next one.

        :param limit: Maximum number of items to return.
        """
        url_variables = None
        base_url = self._get_url(None, url_variables)

        request = operations.GetSessionAuditRequest(
            id=id,
            after=after,
            limit=limit,
        )

        req = self._build_request_async(
            method="GET",
            path="/sessions/{id}/audit",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            allowed_fields=["bearer_auth", "api_key"],
            timeout_ms=self.sdk_configuration.timeout_ms,
        )

        retry_config = None

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="getSessionAudit",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=["Sessions"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=None,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.ListAuditEventsResponse, http_res)
        if utils.match_response(http_res, "400", "application/json"):
            response_data = unmarshal_json_response(errors.ErrBadRequestData, http_res)
            raise errors.ErrBadRequest(response_data, http_res)
        if utils.match_response(http_res, "401", "application/json"):
            response_data = unmarshal_json_response(
                errors.ErrUnauthorizedData, http_res
            )
            raise errors.ErrUnauthorized(response_data, http_res)
        if utils.match_response(http_res, "404", "application/json"):
            response_data = unmarshal_json_response(errors.ErrNotFoundData, http_res)
            raise errors.ErrNotFound(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.AlbusDefaultError("Unexpected response received", http_res)
