"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import AsyncBaseSDK, BaseSDK
from albus_sdk import errors, models, operations, utils
from albus_sdk._hooks import HookContext
from albus_sdk.types import OptionalNullable, UNSET
from albus_sdk.utils import get_security_from_env
from albus_sdk.utils.unmarshal_json_response import unmarshal_json_response
from datetime import datetime
from typing import Any, Optional


class Traces(BaseSDK):
    r"""Find your agent invocations and read what they did."""

    def list_traces(
        self,
        *,
        agent_name: Optional[str] = None,
        agent_revision: Optional[str] = None,
        status: Optional[models.TraceStatus] = None,
        session_id: Optional[str] = None,
        since: Optional[datetime] = None,
        until: Optional[datetime] = None,
        after: Optional[str] = None,
        limit: Optional[int] = 10,
    ) -> models.ListTracesResponse:
        r"""Search traces

        Returns invocations newest first, without their spans. Running invocations are included.


        :param agent_name: Return only invocations of this agent (e.g. \"support-triage\").

        :param agent_revision: Return only invocations of this agent revision (e.g. \"a1b2c3d4\"). Combines with `agent_name`.

        :param status: Return only invocations with this status.

        :param session_id: Return only invocations in this session. An unknown session returns `404`.

        :param since: Return only invocations that started at or after this time. Defaults to 31 days ago.

        :param until: Return only invocations that started at or before this time. Defaults to now and must be after `since`.

        :param after: Continue after this cursor. For list responses, pass the preceding page's `next_cursor`; for session messages, pass the preceding page's last message `cursor`.

        :param limit: Maximum number of traces to return.
        """
        url_variables = None
        base_url = self._get_url(None, url_variables)

        request = operations.ListTracesRequest(
            agent_name=agent_name,
            agent_revision=agent_revision,
            status=status,
            session_id=session_id,
            since=since,
            until=until,
            after=after,
            limit=limit,
        )

        req = self._build_request(
            method="GET",
            path="/traces",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=self.sdk_configuration.timeout_ms,
        )

        retry_config = None

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="listTraces",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=["Traces"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=None,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.ListTracesResponse, http_res)
        if utils.match_response(http_res, "400", "application/json"):
            response_data = unmarshal_json_response(errors.ErrBadRequestData, http_res)
            raise errors.ErrBadRequest(response_data, http_res)
        if utils.match_response(http_res, "401", "application/json"):
            response_data = unmarshal_json_response(
                errors.ErrUnauthorizedData, http_res
            )
            raise errors.ErrUnauthorized(response_data, http_res)
        if utils.match_response(http_res, "404", "application/json"):
            response_data = unmarshal_json_response(errors.ErrNotFoundData, http_res)
            raise errors.ErrNotFound(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.AlbusDefaultError("Unexpected response received", http_res)

    def get_trace(
        self,
        *,
        invocation_key: str,
        payloads: Optional[bool] = True,
        attempts: Optional[operations.Attempts] = "final",
        after: Optional[str] = None,
        limit: Optional[int] = None,
    ) -> operations.GetTraceResponse:
        r"""Get one invocation's trace

        Returns an invocation and its spans in chronological order. Spans may appear shortly after they occur and expire before the invocation does.


        :param invocation_key: Invocation key sent or returned in the `Idempotency-Key` header.

        :param payloads: Whether to include span inputs and outputs. Disabling payloads raises the maximum `limit` to 500. Use the same value on every page.

        :param attempts: Attempts whose spans to return. `final` returns only the latest; `all` includes earlier spans marked `superseded`.

        :param after: Continue after this cursor. For list responses, pass the preceding page's `next_cursor`; for session messages, pass the preceding page's last message `cursor`.

        :param limit: Maximum spans to return. Defaults to 25 with payloads and 500 without; these are also the respective maximums.

        """
        url_variables = None
        base_url = self._get_url(None, url_variables)

        request = operations.GetTraceRequest(
            invocation_key=invocation_key,
            payloads=payloads,
            attempts=attempts,
            after=after,
            limit=limit,
        )

        req = self._build_request(
            method="GET",
            path="/traces/{invocation_key}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=self.sdk_configuration.timeout_ms,
        )

        retry_config = None

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="getTrace",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=["Traces"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=None,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return operations.GetTraceResponse(
                result=unmarshal_json_response(models.TraceResponse, http_res),
                headers={},
            )
        if utils.match_response(http_res, "400", "application/json"):
            response_data = unmarshal_json_response(errors.ErrBadRequestData, http_res)
            raise errors.ErrBadRequest(response_data, http_res)
        if utils.match_response(http_res, "401", "application/json"):
            response_data = unmarshal_json_response(
                errors.ErrUnauthorizedData, http_res
            )
            raise errors.ErrUnauthorized(response_data, http_res)
        if utils.match_response(http_res, "404", "application/json"):
            response_data = unmarshal_json_response(errors.ErrNotFoundData, http_res)
            raise errors.ErrNotFound(response_data, http_res)
        if utils.match_response(http_res, "503", "application/json"):
            response_data = unmarshal_json_response(errors.ErrUnavailableData, http_res)
            raise errors.ErrUnavailable(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.AlbusDefaultError("Unexpected response received", http_res)


class AsyncTraces(AsyncBaseSDK):
    r"""Find your agent invocations and read what they did."""

    async def list_traces(
        self,
        *,
        agent_name: Optional[str] = None,
        agent_revision: Optional[str] = None,
        status: Optional[models.TraceStatus] = None,
        session_id: Optional[str] = None,
        since: Optional[datetime] = None,
        until: Optional[datetime] = None,
        after: Optional[str] = None,
        limit: Optional[int] = 10,
    ) -> models.ListTracesResponse:
        r"""Search traces

        Returns invocations newest first, without their spans. Running invocations are included.


        :param agent_name: Return only invocations of this agent (e.g. \"support-triage\").

        :param agent_revision: Return only invocations of this agent revision (e.g. \"a1b2c3d4\"). Combines with `agent_name`.

        :param status: Return only invocations with this status.

        :param session_id: Return only invocations in this session. An unknown session returns `404`.

        :param since: Return only invocations that started at or after this time. Defaults to 31 days ago.

        :param until: Return only invocations that started at or before this time. Defaults to now and must be after `since`.

        :param after: Continue after this cursor. For list responses, pass the preceding page's `next_cursor`; for session messages, pass the preceding page's last message `cursor`.

        :param limit: Maximum number of traces to return.
        """
        url_variables = None
        base_url = self._get_url(None, url_variables)

        request = operations.ListTracesRequest(
            agent_name=agent_name,
            agent_revision=agent_revision,
            status=status,
            session_id=session_id,
            since=since,
            until=until,
            after=after,
            limit=limit,
        )

        req = self._build_request_async(
            method="GET",
            path="/traces",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=self.sdk_configuration.timeout_ms,
        )

        retry_config = None

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="listTraces",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=["Traces"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=None,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.ListTracesResponse, http_res)
        if utils.match_response(http_res, "400", "application/json"):
            response_data = unmarshal_json_response(errors.ErrBadRequestData, http_res)
            raise errors.ErrBadRequest(response_data, http_res)
        if utils.match_response(http_res, "401", "application/json"):
            response_data = unmarshal_json_response(
                errors.ErrUnauthorizedData, http_res
            )
            raise errors.ErrUnauthorized(response_data, http_res)
        if utils.match_response(http_res, "404", "application/json"):
            response_data = unmarshal_json_response(errors.ErrNotFoundData, http_res)
            raise errors.ErrNotFound(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.AlbusDefaultError("Unexpected response received", http_res)

    async def get_trace(
        self,
        *,
        invocation_key: str,
        payloads: Optional[bool] = True,
        attempts: Optional[operations.Attempts] = "final",
        after: Optional[str] = None,
        limit: Optional[int] = None,
    ) -> operations.GetTraceResponse:
        r"""Get one invocation's trace

        Returns an invocation and its spans in chronological order. Spans may appear shortly after they occur and expire before the invocation does.


        :param invocation_key: Invocation key sent or returned in the `Idempotency-Key` header.

        :param payloads: Whether to include span inputs and outputs. Disabling payloads raises the maximum `limit` to 500. Use the same value on every page.

        :param attempts: Attempts whose spans to return. `final` returns only the latest; `all` includes earlier spans marked `superseded`.

        :param after: Continue after this cursor. For list responses, pass the preceding page's `next_cursor`; for session messages, pass the preceding page's last message `cursor`.

        :param limit: Maximum spans to return. Defaults to 25 with payloads and 500 without; these are also the respective maximums.

        """
        url_variables = None
        base_url = self._get_url(None, url_variables)

        request = operations.GetTraceRequest(
            invocation_key=invocation_key,
            payloads=payloads,
            attempts=attempts,
            after=after,
            limit=limit,
        )

        req = self._build_request_async(
            method="GET",
            path="/traces/{invocation_key}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=self.sdk_configuration.timeout_ms,
        )

        retry_config = None

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="getTrace",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=["Traces"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=None,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return operations.GetTraceResponse(
                result=unmarshal_json_response(models.TraceResponse, http_res),
                headers={},
            )
        if utils.match_response(http_res, "400", "application/json"):
            response_data = unmarshal_json_response(errors.ErrBadRequestData, http_res)
            raise errors.ErrBadRequest(response_data, http_res)
        if utils.match_response(http_res, "401", "application/json"):
            response_data = unmarshal_json_response(
                errors.ErrUnauthorizedData, http_res
            )
            raise errors.ErrUnauthorized(response_data, http_res)
        if utils.match_response(http_res, "404", "application/json"):
            response_data = unmarshal_json_response(errors.ErrNotFoundData, http_res)
            raise errors.ErrNotFound(response_data, http_res)
        if utils.match_response(http_res, "503", "application/json"):
            response_data = unmarshal_json_response(errors.ErrUnavailableData, http_res)
            raise errors.ErrUnavailable(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.AlbusDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.AlbusDefaultError("Unexpected response received", http_res)
