"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import Any, TYPE_CHECKING

from albus_sdk.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .agent import Agent, AgentTypedDict
    from .agentconfig import AgentConfig, AgentConfigTypedDict
    from .agentmeta import AgentMeta, AgentMetaTypedDict
    from .agentrevision import AgentRevision, AgentRevisionTypedDict
    from .agentrevisionmeta import AgentRevisionMeta, AgentRevisionMetaTypedDict
    from .auditevent import AuditEvent, AuditEventTypedDict, Type
    from .authenticatedapikey import AuthenticatedAPIKey, AuthenticatedAPIKeyTypedDict
    from .authenticateduser import AuthenticatedUser, AuthenticatedUserTypedDict
    from .createinviterequest import (
        CreateInviteRequest,
        CreateInviteRequestRole,
        CreateInviteRequestTypedDict,
    )
    from .createsecretrequest import CreateSecretRequest, CreateSecretRequestTypedDict
    from .createtokenrequest import CreateTokenRequest, CreateTokenRequestTypedDict
    from .createtokenresponse import CreateTokenResponse, CreateTokenResponseTypedDict
    from .healthresponse import HealthResponse, HealthResponseTypedDict
    from .invite import Invite, InviteTypedDict
    from .listagentsresponse import ListAgentsResponse, ListAgentsResponseTypedDict
    from .listauditeventsresponse import (
        ListAuditEventsResponse,
        ListAuditEventsResponseTypedDict,
    )
    from .listmodelsresponse import ListModelsResponse, ListModelsResponseTypedDict
    from .listsecretsresponse import ListSecretsResponse, ListSecretsResponseTypedDict
    from .listsessionsresponse import (
        ListSessionsResponse,
        ListSessionsResponseTypedDict,
    )
    from .listtokensresponse import ListTokensResponse, ListTokensResponseTypedDict
    from .mcpserver import MCPServer, MCPServerTypedDict
    from .model import Model, ModelTypedDict
    from .modelmeta import ModelMeta, ModelMetaTypedDict
    from .organizationmembership import (
        OrganizationMembership,
        OrganizationMembershipTypedDict,
    )
    from .provider import Provider, ProviderTypedDict
    from .runsessionrequest import RunSessionRequest, RunSessionRequestTypedDict
    from .runsessionresponse import RunSessionResponse, RunSessionResponseTypedDict
    from .secret import Secret, SecretTypedDict
    from .security import Security, SecurityTypedDict
    from .session import Session, SessionTypedDict, State
    from .sessionmessage import (
        SessionMessage,
        SessionMessageRole,
        SessionMessageTypedDict,
    )
    from .sessionresponse import SessionResponse, SessionResponseTypedDict
    from .token import Token, TokenTypedDict
    from .updatesecretrequest import UpdateSecretRequest, UpdateSecretRequestTypedDict
    from .whoamiresponse import WhoamiResponse, WhoamiResponseTypedDict

__all__ = [
    "Agent",
    "AgentConfig",
    "AgentConfigTypedDict",
    "AgentMeta",
    "AgentMetaTypedDict",
    "AgentRevision",
    "AgentRevisionMeta",
    "AgentRevisionMetaTypedDict",
    "AgentRevisionTypedDict",
    "AgentTypedDict",
    "AuditEvent",
    "AuditEventTypedDict",
    "AuthenticatedAPIKey",
    "AuthenticatedAPIKeyTypedDict",
    "AuthenticatedUser",
    "AuthenticatedUserTypedDict",
    "CreateInviteRequest",
    "CreateInviteRequestRole",
    "CreateInviteRequestTypedDict",
    "CreateSecretRequest",
    "CreateSecretRequestTypedDict",
    "CreateTokenRequest",
    "CreateTokenRequestTypedDict",
    "CreateTokenResponse",
    "CreateTokenResponseTypedDict",
    "HealthResponse",
    "HealthResponseTypedDict",
    "Invite",
    "InviteTypedDict",
    "ListAgentsResponse",
    "ListAgentsResponseTypedDict",
    "ListAuditEventsResponse",
    "ListAuditEventsResponseTypedDict",
    "ListModelsResponse",
    "ListModelsResponseTypedDict",
    "ListSecretsResponse",
    "ListSecretsResponseTypedDict",
    "ListSessionsResponse",
    "ListSessionsResponseTypedDict",
    "ListTokensResponse",
    "ListTokensResponseTypedDict",
    "MCPServer",
    "MCPServerTypedDict",
    "Model",
    "ModelMeta",
    "ModelMetaTypedDict",
    "ModelTypedDict",
    "OrganizationMembership",
    "OrganizationMembershipTypedDict",
    "Provider",
    "ProviderTypedDict",
    "RunSessionRequest",
    "RunSessionRequestTypedDict",
    "RunSessionResponse",
    "RunSessionResponseTypedDict",
    "Secret",
    "SecretTypedDict",
    "Security",
    "SecurityTypedDict",
    "Session",
    "SessionMessage",
    "SessionMessageRole",
    "SessionMessageTypedDict",
    "SessionResponse",
    "SessionResponseTypedDict",
    "SessionTypedDict",
    "State",
    "Token",
    "TokenTypedDict",
    "Type",
    "UpdateSecretRequest",
    "UpdateSecretRequestTypedDict",
    "WhoamiResponse",
    "WhoamiResponseTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "Agent": ".agent",
    "AgentTypedDict": ".agent",
    "AgentConfig": ".agentconfig",
    "AgentConfigTypedDict": ".agentconfig",
    "AgentMeta": ".agentmeta",
    "AgentMetaTypedDict": ".agentmeta",
    "AgentRevision": ".agentrevision",
    "AgentRevisionTypedDict": ".agentrevision",
    "AgentRevisionMeta": ".agentrevisionmeta",
    "AgentRevisionMetaTypedDict": ".agentrevisionmeta",
    "AuditEvent": ".auditevent",
    "AuditEventTypedDict": ".auditevent",
    "Type": ".auditevent",
    "AuthenticatedAPIKey": ".authenticatedapikey",
    "AuthenticatedAPIKeyTypedDict": ".authenticatedapikey",
    "AuthenticatedUser": ".authenticateduser",
    "AuthenticatedUserTypedDict": ".authenticateduser",
    "CreateInviteRequest": ".createinviterequest",
    "CreateInviteRequestRole": ".createinviterequest",
    "CreateInviteRequestTypedDict": ".createinviterequest",
    "CreateSecretRequest": ".createsecretrequest",
    "CreateSecretRequestTypedDict": ".createsecretrequest",
    "CreateTokenRequest": ".createtokenrequest",
    "CreateTokenRequestTypedDict": ".createtokenrequest",
    "CreateTokenResponse": ".createtokenresponse",
    "CreateTokenResponseTypedDict": ".createtokenresponse",
    "HealthResponse": ".healthresponse",
    "HealthResponseTypedDict": ".healthresponse",
    "Invite": ".invite",
    "InviteTypedDict": ".invite",
    "ListAgentsResponse": ".listagentsresponse",
    "ListAgentsResponseTypedDict": ".listagentsresponse",
    "ListAuditEventsResponse": ".listauditeventsresponse",
    "ListAuditEventsResponseTypedDict": ".listauditeventsresponse",
    "ListModelsResponse": ".listmodelsresponse",
    "ListModelsResponseTypedDict": ".listmodelsresponse",
    "ListSecretsResponse": ".listsecretsresponse",
    "ListSecretsResponseTypedDict": ".listsecretsresponse",
    "ListSessionsResponse": ".listsessionsresponse",
    "ListSessionsResponseTypedDict": ".listsessionsresponse",
    "ListTokensResponse": ".listtokensresponse",
    "ListTokensResponseTypedDict": ".listtokensresponse",
    "MCPServer": ".mcpserver",
    "MCPServerTypedDict": ".mcpserver",
    "Model": ".model",
    "ModelTypedDict": ".model",
    "ModelMeta": ".modelmeta",
    "ModelMetaTypedDict": ".modelmeta",
    "OrganizationMembership": ".organizationmembership",
    "OrganizationMembershipTypedDict": ".organizationmembership",
    "Provider": ".provider",
    "ProviderTypedDict": ".provider",
    "RunSessionRequest": ".runsessionrequest",
    "RunSessionRequestTypedDict": ".runsessionrequest",
    "RunSessionResponse": ".runsessionresponse",
    "RunSessionResponseTypedDict": ".runsessionresponse",
    "Secret": ".secret",
    "SecretTypedDict": ".secret",
    "Security": ".security",
    "SecurityTypedDict": ".security",
    "Session": ".session",
    "SessionTypedDict": ".session",
    "State": ".session",
    "SessionMessage": ".sessionmessage",
    "SessionMessageRole": ".sessionmessage",
    "SessionMessageTypedDict": ".sessionmessage",
    "SessionResponse": ".sessionresponse",
    "SessionResponseTypedDict": ".sessionresponse",
    "Token": ".token",
    "TokenTypedDict": ".token",
    "UpdateSecretRequest": ".updatesecretrequest",
    "UpdateSecretRequestTypedDict": ".updatesecretrequest",
    "WhoamiResponse": ".whoamiresponse",
    "WhoamiResponseTypedDict": ".whoamiresponse",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
