"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .agentrevision import AgentRevision, AgentRevisionTypedDict
from .agentrevisionmeta import AgentRevisionMeta, AgentRevisionMetaTypedDict
from albus_sdk.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class AgentTypedDict(TypedDict):
    r"""An agent identified by name, with its current revision's full configuration and the list of all its revisions newest first."""

    name: str
    r"""The agent's name."""
    current: AgentRevisionTypedDict
    r"""One revision of an agent, with its full configuration."""
    revisions: List[AgentRevisionMetaTypedDict]
    r"""All revisions of the agent, newest first."""


class Agent(BaseModel):
    r"""An agent identified by name, with its current revision's full configuration and the list of all its revisions newest first."""

    name: str
    r"""The agent's name."""

    current: AgentRevision
    r"""One revision of an agent, with its full configuration."""

    revisions: List[AgentRevisionMeta]
    r"""All revisions of the agent, newest first."""
