"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from albus_sdk.types import BaseModel
from datetime import datetime
from typing_extensions import TypedDict


class AgentRevisionMetaTypedDict(TypedDict):
    r"""A reference to one agent revision, without its configuration."""

    revision: str
    r"""Identifier of this agent revision."""
    created_at: datetime
    r"""When this revision first ran."""


class AgentRevisionMeta(BaseModel):
    r"""A reference to one agent revision, without its configuration."""

    revision: str
    r"""Identifier of this agent revision."""

    created_at: datetime
    r"""When this revision first ran."""
