"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from albus_sdk.types import BaseModel, UNSET_SENTINEL, UnrecognizedStr
from datetime import datetime
from pydantic import model_serializer
from typing import Any, Dict, Literal, Optional, Union
from typing_extensions import NotRequired, TypedDict


AuditEventType = Union[
    Literal[
        "agent_invocation",
        "agent_step",
        "model_call",
        "tool_call",
        "harness_exit",
        "invocation_failed",
        "invocation_succeeded",
        "llm_call",
        "tool_result",
        "run_failed",
        "run_succeeded",
    ],
    UnrecognizedStr,
]
r"""The kind of event (e.g. \"agent_invocation\" for the request that started the invocation, \"agent_step\" for one turn, how it ended, and how long it took, \"model_call\" for a model call and the tool calls it requested, \"tool_call\" for an executed tool call and its output). Events recorded earlier use \"llm_call\", \"tool_result\", \"run_failed\" and \"run_succeeded\" for four of those kinds.

"""


class AuditEventTypedDict(TypedDict):
    id: str
    r"""Stable identifier of this audit event within the session."""
    session_id: str
    r"""The session this event belongs to."""
    invocation_key: str
    r"""Key of the invocation during which this event occurred.

    """
    type: AuditEventType
    r"""The kind of event (e.g. \"agent_invocation\" for the request that started the invocation, \"agent_step\" for one turn, how it ended, and how long it took, \"model_call\" for a model call and the tool calls it requested, \"tool_call\" for an executed tool call and its output). Events recorded earlier use \"llm_call\", \"tool_result\", \"run_failed\" and \"run_succeeded\" for four of those kinds.

    """
    payload: Dict[str, Any]
    r"""The event's details, whose shape depends on `type` (e.g. the model, its response, usage, and requested tool calls for \"model_call\"; the call's arguments, response, status, timing, and MCP server URL for \"tool_call\"). A large value may be stored truncated, marked by a flag such as `requestTruncated`; a truncated `request`, `response` or `content` also carries the byte count and SHA-256 digest of the complete value, in fields such as `requestBytes` and `requestSha256`. A \"model_call\"'s `request` is the input the model was given, so an invocation's final call using `output_format` includes turns Albus adds to obtain the JSON answer.

    """
    event_time: datetime
    r"""When the event occurred."""
    agent_revision: NotRequired[str]
    r"""The agent revision the invocation ran (e.g. \"a1b2c3d4\")."""


class AuditEvent(BaseModel):
    id: str
    r"""Stable identifier of this audit event within the session."""

    session_id: str
    r"""The session this event belongs to."""

    invocation_key: str
    r"""Key of the invocation during which this event occurred.

    """

    type: AuditEventType
    r"""The kind of event (e.g. \"agent_invocation\" for the request that started the invocation, \"agent_step\" for one turn, how it ended, and how long it took, \"model_call\" for a model call and the tool calls it requested, \"tool_call\" for an executed tool call and its output). Events recorded earlier use \"llm_call\", \"tool_result\", \"run_failed\" and \"run_succeeded\" for four of those kinds.

    """

    payload: Dict[str, Any]
    r"""The event's details, whose shape depends on `type` (e.g. the model, its response, usage, and requested tool calls for \"model_call\"; the call's arguments, response, status, timing, and MCP server URL for \"tool_call\"). A large value may be stored truncated, marked by a flag such as `requestTruncated`; a truncated `request`, `response` or `content` also carries the byte count and SHA-256 digest of the complete value, in fields such as `requestBytes` and `requestSha256`. A \"model_call\"'s `request` is the input the model was given, so an invocation's final call using `output_format` includes turns Albus adds to obtain the JSON answer.

    """

    event_time: datetime
    r"""When the event occurred."""

    agent_revision: Optional[str] = None
    r"""The agent revision the invocation ran (e.g. \"a1b2c3d4\")."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["agent_revision"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
