"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .organizationmembership import (
    OrganizationMembership,
    OrganizationMembershipTypedDict,
)
from albus_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class AuthenticatedUserTypedDict(TypedDict):
    user_id: str
    r"""Unique user identifier"""
    email: str
    r"""User's email address"""
    active_organization: OrganizationMembershipTypedDict
    r"""The organization the request acts on: the one named by the X-Albus-Organization header, or the one the user joined first.

    """
    organizations: List[OrganizationMembershipTypedDict]
    r"""Every organization the user belongs to, with their roles."""
    name: NotRequired[str]
    r"""User's display name"""
    roles: NotRequired[List[str]]
    r"""Roles in the active organization."""
    issued_at: NotRequired[int]
    r"""Token issue timestamp (Unix epoch)"""
    expires_at: NotRequired[int]
    r"""Token expiration timestamp (Unix epoch)"""


class AuthenticatedUser(BaseModel):
    user_id: str
    r"""Unique user identifier"""

    email: str
    r"""User's email address"""

    active_organization: OrganizationMembership
    r"""The organization the request acts on: the one named by the X-Albus-Organization header, or the one the user joined first.

    """

    organizations: List[OrganizationMembership]
    r"""Every organization the user belongs to, with their roles."""

    name: Optional[str] = None
    r"""User's display name"""

    roles: Optional[List[str]] = None
    r"""Roles in the active organization."""

    issued_at: Optional[int] = None
    r"""Token issue timestamp (Unix epoch)"""

    expires_at: Optional[int] = None
    r"""Token expiration timestamp (Unix epoch)"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["name", "roles", "issued_at", "expires_at"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
