"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from albus_sdk.types import BaseModel
from typing_extensions import TypedDict


class CancelSessionResponseTypedDict(TypedDict):
    invocation_key: str
    r"""The key of the invocation being canceled."""


class CancelSessionResponse(BaseModel):
    invocation_key: str
    r"""The key of the invocation being canceled."""
