"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from albus_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Literal, Optional
from typing_extensions import NotRequired, TypedDict


CreateInviteRequestRole = Literal[
    "admin",
    "member",
]
r"""Role to grant the invitee. Defaults to admin when inviting to a new organization and member when inviting into an existing one.

"""


class CreateInviteRequestTypedDict(TypedDict):
    email: str
    r"""Email address of the person to invite."""
    role: NotRequired[CreateInviteRequestRole]
    r"""Role to grant the invitee. Defaults to admin when inviting to a new organization and member when inviting into an existing one.

    """
    organization_id: NotRequired[str]
    r"""Organization to invite the user into (e.g. \"42\"). Omit to create a new organization for the user on their first sign-in.

    """


class CreateInviteRequest(BaseModel):
    email: str
    r"""Email address of the person to invite."""

    role: Optional[CreateInviteRequestRole] = None
    r"""Role to grant the invitee. Defaults to admin when inviting to a new organization and member when inviting into an existing one.

    """

    organization_id: Optional[str] = None
    r"""Organization to invite the user into (e.g. \"42\"). Omit to create a new organization for the user on their first sign-in.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["role", "organization_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
