"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from albus_sdk.types import BaseModel
from datetime import datetime
from typing_extensions import TypedDict


class CreateTokenResponseTypedDict(TypedDict):
    id: str
    r"""Globally unique lookup identifier."""
    name: str
    r"""Human-readable display name."""
    token: str
    r"""The full API token value (format: alb-<id>-<secret>).
    Returned only at creation time — it cannot be retrieved again.

    """
    created_at: datetime


class CreateTokenResponse(BaseModel):
    id: str
    r"""Globally unique lookup identifier."""

    name: str
    r"""Human-readable display name."""

    token: str
    r"""The full API token value (format: alb-<id>-<secret>).
    Returned only at creation time — it cannot be retrieved again.

    """

    created_at: datetime
