"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from albus_sdk.types import BaseModel
from typing_extensions import TypedDict


class CreateSecretRequestTypedDict(TypedDict):
    name: str
    value: str
    r"""The secret value."""


class CreateSecretRequest(BaseModel):
    name: str

    value: str
    r"""The secret value."""
