"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from albus_sdk.types import BaseModel
from typing_extensions import TypedDict


class CreditBalanceResponseTypedDict(TypedDict):
    balance_usd: str
    r"""Your current credit balance as a decimal USD string (e.g. \"14.99\"). Negative when overdrawn.

    """


class CreditBalanceResponse(BaseModel):
    balance_usd: str
    r"""Your current credit balance as a decimal USD string (e.g. \"14.99\"). Negative when overdrawn.

    """
