"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from albus_sdk.types import BaseModel, UnrecognizedStr
from datetime import datetime
from typing import Literal, Union
from typing_extensions import TypedDict


Kind = Union[
    Literal[
        "purchase",
        "grant",
        "usage_burn",
        "adjustment",
    ],
    UnrecognizedStr,
]
r"""What moved the balance: a paid purchase, an operator grant, a usage charge, or a manual adjustment.

"""


class CreditLedgerEntryTypedDict(TypedDict):
    kind: Kind
    r"""What moved the balance: a paid purchase, an operator grant, a usage charge, or a manual adjustment.

    """
    amount_usd: str
    r"""The signed decimal USD amount the entry moved the balance by: positive for money in, negative for usage charged.

    """
    reference: str
    r"""Identifies what the entry paid for or charged (e.g. the payment for a purchase, the metering window for a usage charge).

    """
    created_at: datetime
    r"""When the entry was recorded."""


class CreditLedgerEntry(BaseModel):
    kind: Kind
    r"""What moved the balance: a paid purchase, an operator grant, a usage charge, or a manual adjustment.

    """

    amount_usd: str
    r"""The signed decimal USD amount the entry moved the balance by: positive for money in, negative for usage charged.

    """

    reference: str
    r"""Identifies what the entry paid for or charged (e.g. the payment for a purchase, the metering window for a usage charge).

    """

    created_at: datetime
    r"""When the entry was recorded."""
