"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from albus_sdk.types import BaseModel, UNSET_SENTINEL
from albus_sdk.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetSessionRequestTypedDict(TypedDict):
    id: str
    r"""Client-provided session identifier. Use the same value across requests to continue the same agent session."""
    after: NotRequired[str]
    r"""Opaque pagination cursor. Return only items positioned after it; pass a value obtained from a previous page to fetch the next one.

    """
    limit: NotRequired[int]
    r"""Maximum number of items to return."""


class GetSessionRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Client-provided session identifier. Use the same value across requests to continue the same agent session."""

    after: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Opaque pagination cursor. Return only items positioned after it; pass a value obtained from a previous page to fetch the next one.

    """

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 100
    r"""Maximum number of items to return."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["after", "limit"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
