"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .session import Session, SessionTypedDict
from albus_sdk.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class ListSessionsResponseTypedDict(TypedDict):
    sessions: List[SessionTypedDict]


class ListSessionsResponse(BaseModel):
    sessions: List[Session]
