"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .invite import Invite, InviteTypedDict
from albus_sdk.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class ListInvitesResponseTypedDict(TypedDict):
    invites: List[InviteTypedDict]


class ListInvitesResponse(BaseModel):
    invites: List[Invite]
