"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .modelmeta import ModelMeta, ModelMetaTypedDict
from albus_sdk.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class ListModelsResponseTypedDict(TypedDict):
    models: List[ModelMetaTypedDict]


class ListModelsResponse(BaseModel):
    models: List[ModelMeta]
