"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .memorygroup import MemoryGroup, MemoryGroupTypedDict
from albus_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class ListMemoryGroupsResponseTypedDict(TypedDict):
    memory_groups: List[MemoryGroupTypedDict]
    next_cursor: NotRequired[str]
    r"""Cursor for the next page. Pass it as `after` to fetch the following groups. Omitted when there are no more groups.

    """


class ListMemoryGroupsResponse(BaseModel):
    memory_groups: List[MemoryGroup]

    next_cursor: Optional[str] = None
    r"""Cursor for the next page. Pass it as `after` to fetch the following groups. Omitted when there are no more groups.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["next_cursor"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
