"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .token import Token, TokenTypedDict
from albus_sdk.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class ListTokensResponseTypedDict(TypedDict):
    tokens: List[TokenTypedDict]


class ListTokensResponse(BaseModel):
    tokens: List[Token]
