"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .albusidentityjwtauth import AlbusIdentityJWTAuth, AlbusIdentityJWTAuthTypedDict
from .bearertokenauth import BearerTokenAuth, BearerTokenAuthTypedDict
from .oauth2clientcredentialsauth import (
    OAuth2ClientCredentialsAuth,
    OAuth2ClientCredentialsAuthTypedDict,
)
from albus_sdk.types import BaseModel
from albus_sdk.utils.unions import parse_open_union
from functools import partial
from pydantic import ConfigDict, model_serializer
from pydantic.functional_validators import BeforeValidator
from typing import Any, Literal, Union
from typing_extensions import Annotated, TypeAliasType


MCPServerAuthTypedDict = TypeAliasType(
    "MCPServerAuthTypedDict",
    Union[
        AlbusIdentityJWTAuthTypedDict,
        BearerTokenAuthTypedDict,
        OAuth2ClientCredentialsAuthTypedDict,
    ],
)
r"""The credential Albus presents to an MCP server, chosen by type.

"""


class UnknownMCPServerAuth(BaseModel):
    r"""A MCPServerAuth variant the SDK doesn't recognize. Preserves the raw payload."""

    type: Literal["UNKNOWN"] = "UNKNOWN"
    raw: Any
    is_unknown: Literal[True] = True

    model_config = ConfigDict(frozen=True)

    @model_serializer(mode="plain")
    def serialize_raw(self) -> Any:
        return self.raw


_MCP_SERVER_AUTH_VARIANTS: dict[str, Any] = {
    "albus_identity_jwt": AlbusIdentityJWTAuth,
    "oauth2_client_credentials": OAuth2ClientCredentialsAuth,
    "bearer": BearerTokenAuth,
}


MCPServerAuth = Annotated[
    Union[
        AlbusIdentityJWTAuth,
        OAuth2ClientCredentialsAuth,
        BearerTokenAuth,
        UnknownMCPServerAuth,
    ],
    BeforeValidator(
        partial(
            parse_open_union,
            disc_key="type",
            variants=_MCP_SERVER_AUTH_VARIANTS,
            unknown_cls=UnknownMCPServerAuth,
            union_name="MCPServerAuth",
        )
    ),
]
r"""The credential Albus presents to an MCP server, chosen by type.

"""
