"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .mcpserverauth import MCPServerAuth, MCPServerAuthTypedDict
from albus_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Dict, List, Optional
from typing_extensions import NotRequired, TypedDict


class MCPServerTypedDict(TypedDict):
    name: str
    r"""Unique alias for the server. It prefixes the server's tool names (e.g. \"github\" exposes its search tool as \"github__search\").

    """
    url: str
    r"""The server's Streamable HTTP endpoint."""
    headers: NotRequired[Dict[str, str]]
    r"""HTTP headers sent to the server, with secret values as secret references (e.g. \"albus.sh/secrets/github-mcp\"); this is also where to send an API key or other non-Bearer credential.

    """
    allowed_tools: NotRequired[List[str]]
    r"""The server tools the model may call. Omit to allow all of them.

    """
    auth: NotRequired[MCPServerAuthTypedDict]
    r"""How Albus authenticates to the server. Omit for the default, AlbusIdentityJWTAuth, which needs no credential from you; see that schema for what the server must verify. Setting \"headers.Authorization\" instead sends that header verbatim.

    """


class MCPServer(BaseModel):
    name: str
    r"""Unique alias for the server. It prefixes the server's tool names (e.g. \"github\" exposes its search tool as \"github__search\").

    """

    url: str
    r"""The server's Streamable HTTP endpoint."""

    headers: Optional[Dict[str, str]] = None
    r"""HTTP headers sent to the server, with secret values as secret references (e.g. \"albus.sh/secrets/github-mcp\"); this is also where to send an API key or other non-Bearer credential.

    """

    allowed_tools: Optional[List[str]] = None
    r"""The server tools the model may call. Omit to allow all of them.

    """

    auth: Optional[MCPServerAuth] = None
    r"""How Albus authenticates to the server. Omit for the default, AlbusIdentityJWTAuth, which needs no credential from you; see that schema for what the server must verify. Setting \"headers.Authorization\" instead sends that header verbatim.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["headers", "allowed_tools", "auth"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
