"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from albus_sdk.types import BaseModel, UnrecognizedStr
from typing import List, Literal, Union
from typing_extensions import TypedDict


Generation = Union[
    Literal[
        "agent",
        "end_of_invocation",
    ],
    UnrecognizedStr,
]


class MemoryConfigTypedDict(TypedDict):
    r"""Configures durable memory shared by invocations in the same group."""

    group: str
    r"""Key identifying invocations that share memory."""
    generation: List[Generation]
    r"""Points when this agent may generate memories."""


class MemoryConfig(BaseModel):
    r"""Configures durable memory shared by invocations in the same group."""

    group: str
    r"""Key identifying invocations that share memory."""

    generation: List[Generation]
    r"""Points when this agent may generate memories."""
