"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .modelpricing import ModelPricing, ModelPricingTypedDict
from albus_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ModelMetaTypedDict(TypedDict):
    r"""A model Albus can run, and the provider serving it."""

    name: str
    r"""Model identifier to send as the agent's model name (e.g. \"gemini-3.6-flash\").

    """
    provider: str
    r"""Provider serving this model (e.g. \"google_agent_studio\", or \"open_weight\" for open-weight models).

    """
    pricing: NotRequired[ModelPricingTypedDict]
    r"""What the model currently costs, as decimal USD strings per one million tokens (e.g. \"1.25\"). Absent when the model is not yet priced.

    """


class ModelMeta(BaseModel):
    r"""A model Albus can run, and the provider serving it."""

    name: str
    r"""Model identifier to send as the agent's model name (e.g. \"gemini-3.6-flash\").

    """

    provider: str
    r"""Provider serving this model (e.g. \"google_agent_studio\", or \"open_weight\" for open-weight models).

    """

    pricing: Optional[ModelPricing] = None
    r"""What the model currently costs, as decimal USD strings per one million tokens (e.g. \"1.25\"). Absent when the model is not yet priced.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["pricing"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
