"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from albus_sdk.types import BaseModel
from typing_extensions import TypedDict


class ModelPricingTypedDict(TypedDict):
    r"""What the model currently costs, as decimal USD strings per one million tokens (e.g. \"1.25\"). Absent when the model is not yet priced."""

    input_usd_per_mtok: str
    r"""Price per million input tokens."""
    cached_input_usd_per_mtok: str
    r"""Price per million cached input tokens."""
    output_usd_per_mtok: str
    r"""Price per million output tokens."""
    thoughts_usd_per_mtok: str
    r"""Price per million reasoning (thinking) tokens."""


class ModelPricing(BaseModel):
    r"""What the model currently costs, as decimal USD strings per one million tokens (e.g. \"1.25\"). Absent when the model is not yet priced."""

    input_usd_per_mtok: str
    r"""Price per million input tokens."""

    cached_input_usd_per_mtok: str
    r"""Price per million cached input tokens."""

    output_usd_per_mtok: str
    r"""Price per million output tokens."""

    thoughts_usd_per_mtok: str
    r"""Price per million reasoning (thinking) tokens."""
