"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from albus_sdk.types import BaseModel, UNSET_SENTINEL
from albus_sdk.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import List, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class OAuth2ClientCredentialsAuthTypedDict(TypedDict):
    r"""An access token obtained from your identity provider with the OAuth 2.0 client credentials grant."""

    token_url: str
    r"""The identity provider's HTTPS token endpoint."""
    client_id: str
    r"""The client identifier, as a secret reference or a literal.

    """
    client_secret: str
    r"""The client secret, as a secret reference (e.g. \"albus.sh/secrets/idp-client-secret\"), never a raw value.

    """
    type: Literal["oauth2_client_credentials"]
    audience: NotRequired[str]
    r"""The audience requested from the identity provider."""
    scopes: NotRequired[List[str]]
    r"""The scopes requested from the identity provider."""


class OAuth2ClientCredentialsAuth(BaseModel):
    r"""An access token obtained from your identity provider with the OAuth 2.0 client credentials grant."""

    token_url: str
    r"""The identity provider's HTTPS token endpoint."""

    client_id: str
    r"""The client identifier, as a secret reference or a literal.

    """

    client_secret: str
    r"""The client secret, as a secret reference (e.g. \"albus.sh/secrets/idp-client-secret\"), never a raw value.

    """

    type: Annotated[
        Annotated[
            Literal["oauth2_client_credentials"],
            AfterValidator(validate_const("oauth2_client_credentials")),
        ],
        pydantic.Field(alias="type"),
    ] = "oauth2_client_credentials"

    audience: Optional[str] = None
    r"""The audience requested from the identity provider."""

    scopes: Optional[List[str]] = None
    r"""The scopes requested from the identity provider."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["audience", "scopes"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    OAuth2ClientCredentialsAuth.model_rebuild()
except NameError:
    pass
