"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from albus_sdk.types import BaseModel
from datetime import datetime
from typing_extensions import TypedDict


class OrganizationTypedDict(TypedDict):
    id: str
    r"""Organization identifier"""
    name: str
    r"""Organization display name"""
    created_at: datetime
    r"""When the organization was created."""


class Organization(BaseModel):
    id: str
    r"""Organization identifier"""

    name: str
    r"""Organization display name"""

    created_at: datetime
    r"""When the organization was created."""
