"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from albus_sdk.types import BaseModel
from datetime import datetime
from typing_extensions import TypedDict


class OrganizationTypedDict(TypedDict):
    id: str
    r"""Organization identifier"""
    name: str
    r"""Organization display name"""
    created_at: datetime
    r"""When the organization was created."""
    issuer: str
    r"""OpenID issuer of the identity tokens Albus presents to the organization's MCP servers; verifiers use it as the expected `iss` claim and to discover the signing keys."""


class Organization(BaseModel):
    id: str
    r"""Organization identifier"""

    name: str
    r"""Organization display name"""

    created_at: datetime
    r"""When the organization was created."""

    issuer: str
    r"""OpenID issuer of the identity tokens Albus presents to the organization's MCP servers; verifiers use it as the expected `iss` claim and to discover the signing keys."""
