"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .role import Role
from albus_sdk.types import BaseModel
from datetime import datetime
from typing_extensions import TypedDict


class OrganizationMemberTypedDict(TypedDict):
    user_id: str
    r"""User identifier"""
    email: str
    r"""Email address"""
    name: str
    r"""Display name"""
    role: Role
    r"""A member's role in an organization."""
    joined_at: datetime
    r"""When the user joined the organization."""


class OrganizationMember(BaseModel):
    user_id: str
    r"""User identifier"""

    email: str
    r"""Email address"""

    name: str
    r"""Display name"""

    role: Role
    r"""A member's role in an organization."""

    joined_at: datetime
    r"""When the user joined the organization."""
