"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .agentconfig import AgentConfig, AgentConfigTypedDict
from albus_sdk.types import BaseModel
from typing_extensions import TypedDict


class RunSessionRequestTypedDict(TypedDict):
    user_prompt: str
    r"""The user prompt driving this invocation."""
    agent_name: str
    r"""Human-readable name identifying the agent (e.g. \"support-triage\"). Runs sharing a name are grouped as one agent; each distinct configuration under it becomes a revision.

    """
    agent: AgentConfigTypedDict
    r"""The agent configuration for a run: the model, tools, instructions, and MCP servers that define its behavior. Runs with the same configuration share a revision.

    """


class RunSessionRequest(BaseModel):
    user_prompt: str
    r"""The user prompt driving this invocation."""

    agent_name: str
    r"""Human-readable name identifying the agent (e.g. \"support-triage\"). Runs sharing a name are grouped as one agent; each distinct configuration under it becomes a revision.

    """

    agent: AgentConfig
    r"""The agent configuration for a run: the model, tools, instructions, and MCP servers that define its behavior. Runs with the same configuration share a revision.

    """
