"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .session import Session, SessionTypedDict
from .sessionmessage import SessionMessage, SessionMessageTypedDict
from albus_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class RunSessionResponseTypedDict(TypedDict):
    session: SessionTypedDict
    message: NotRequired[SessionMessageTypedDict]
    r"""The assistant message this invocation produced. Absent when the invocation has not answered yet — a call with `wait_timeout_seconds=0`, or a wait that returned before the response existed. Use `GET /sessions/{id}` to read it later.

    """


class RunSessionResponse(BaseModel):
    session: Session

    message: Optional[SessionMessage] = None
    r"""The assistant message this invocation produced. Absent when the invocation has not answered yet — a call with `wait_timeout_seconds=0`, or a wait that returned before the response existed. Use `GET /sessions/{id}` to read it later.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["message"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
