"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .runsessionrequest import RunSessionRequest, RunSessionRequestTypedDict
from .sessionresponse import SessionResponse, SessionResponseTypedDict
from albus_sdk.types import BaseModel, UNSET_SENTINEL
from albus_sdk.utils import (
    FieldMetadata,
    HeaderMetadata,
    PathParamMetadata,
    QueryParamMetadata,
    RequestMetadata,
)
import pydantic
from pydantic import model_serializer
from typing import Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class RunSessionRequestRequestTypedDict(TypedDict):
    id: str
    r"""Client-provided session identifier. Use the same value across requests to continue the same agent session."""
    body: RunSessionRequestTypedDict
    idempotency_key: NotRequired[str]
    r"""Optional but strongly encouraged. Uniquely identifies this invocation of the session; reuse the same value to safely retry a request, and a new value starts a new invocation. When omitted, the server generates a key for the invocation and returns it in the Idempotency-Key response header, but the request is not retry-safe.

    """
    wait: NotRequired[bool]
    r"""When true, long-poll: block until the invocation's assistant response is available before returning.

    """
    wait_timeout: NotRequired[int]
    r"""Maximum time in seconds to block when wait=true. Omit to wait indefinitely. Ignored when wait is false.

    """


class RunSessionRequestRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Client-provided session identifier. Use the same value across requests to continue the same agent session."""

    body: Annotated[
        RunSessionRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    idempotency_key: Annotated[
        Optional[str],
        pydantic.Field(alias="Idempotency-Key"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = None
    r"""Optional but strongly encouraged. Uniquely identifies this invocation of the session; reuse the same value to safely retry a request, and a new value starts a new invocation. When omitted, the server generates a key for the invocation and returns it in the Idempotency-Key response header, but the request is not retry-safe.

    """

    wait: Annotated[
        Optional[bool],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = False
    r"""When true, long-poll: block until the invocation's assistant response is available before returning.

    """

    wait_timeout: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Maximum time in seconds to block when wait=true. Omit to wait indefinitely. Ignored when wait is false.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["Idempotency-Key", "wait", "wait_timeout"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class RunSessionResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: SessionResponseTypedDict


class RunSessionResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: SessionResponse
