"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .mcpserver import MCPServer, MCPServerTypedDict
from .model import Model, ModelTypedDict
from albus_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class RunSessionRequestTypedDict(TypedDict):
    user_prompt: str
    r"""The user prompt driving this invocation."""
    model: ModelTypedDict
    tools: NotRequired[List[str]]
    r"""Names of the tools the model may call (e.g. \"WEB_SEARCH\")."""
    system_prompt: NotRequired[str]
    r"""System instructions for the model. Uses a default if omitted."""
    max_steps: NotRequired[int]
    r"""Max model steps before the run stops. Uses a default if omitted."""
    mcp_servers: NotRequired[List[MCPServerTypedDict]]
    r"""MCP servers whose tools are offered to the model."""


class RunSessionRequest(BaseModel):
    user_prompt: str
    r"""The user prompt driving this invocation."""

    model: Model

    tools: Optional[List[str]] = None
    r"""Names of the tools the model may call (e.g. \"WEB_SEARCH\")."""

    system_prompt: Optional[str] = None
    r"""System instructions for the model. Uses a default if omitted."""

    max_steps: Optional[int] = None
    r"""Max model steps before the run stops. Uses a default if omitted."""

    mcp_servers: Optional[List[MCPServer]] = None
    r"""MCP servers whose tools are offered to the model."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["tools", "system_prompt", "max_steps", "mcp_servers"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
