"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from albus_sdk.types import BaseModel
from typing_extensions import TypedDict


class SecretTypedDict(TypedDict):
    name: str
    masked_value: str
    r"""The secret value with all but the last 3 characters masked."""


class Secret(BaseModel):
    name: str

    masked_value: str
    r"""The secret value with all but the last 3 characters masked."""
