"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from albus_sdk.types import UnrecognizedStr
from typing import Literal, Union


SessionState = Union[
    Literal[
        "RUNNING",
        "DONE",
        "FAILED",
        "CANCELED",
    ],
    UnrecognizedStr,
]
r"""Lifecycle state of the session: `RUNNING` while an invocation is in flight, otherwise how its latest invocation ended.

"""
