"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .session import Session, SessionTypedDict
from .sessionmessage import SessionMessage, SessionMessageTypedDict
from albus_sdk.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class SessionResponseTypedDict(TypedDict):
    session: SessionTypedDict
    messages: List[SessionMessageTypedDict]


class SessionResponse(BaseModel):
    session: Session

    messages: List[SessionMessage]
