"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from albus_sdk.types import BaseModel, UnrecognizedStr
from datetime import datetime
from typing import Literal, Union
from typing_extensions import TypedDict


SessionMessageRole = Union[
    Literal[
        "user",
        "assistant",
    ],
    UnrecognizedStr,
]


class SessionMessageTypedDict(TypedDict):
    cursor: int
    r"""Monotonic per-session position of this message."""
    invocation_id: str
    r"""The invocation that produced this message."""
    role: SessionMessageRole
    content: str
    created_at: datetime


class SessionMessage(BaseModel):
    cursor: int
    r"""Monotonic per-session position of this message."""

    invocation_id: str
    r"""The invocation that produced this message."""

    role: SessionMessageRole

    content: str

    created_at: datetime
