"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from albus_sdk.types import BaseModel, UNSET_SENTINEL, UnrecognizedStr
from datetime import datetime
from pydantic import model_serializer
from typing import Literal, Optional, Union
from typing_extensions import NotRequired, TypedDict


State = Union[
    Literal[
        "RUNNING",
        "DONE",
        "FAILED",
        "CANCELED",
    ],
    UnrecognizedStr,
]
r"""Lifecycle state of the session."""


class SessionTypedDict(TypedDict):
    id: str
    r"""Client-provided session identifier."""
    state: State
    r"""Lifecycle state of the session."""
    invocation_count: int
    r"""Number of times this session has been run."""
    created_at: datetime
    updated_at: datetime
    current_invocation_id: NotRequired[str]
    r"""The invocation currently running, if any. Omitted when the session is idle.

    """


class Session(BaseModel):
    id: str
    r"""Client-provided session identifier."""

    state: State
    r"""Lifecycle state of the session."""

    invocation_count: int
    r"""Number of times this session has been run."""

    created_at: datetime

    updated_at: datetime

    current_invocation_id: Optional[str] = None
    r"""The invocation currently running, if any. Omitted when the session is idle.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["current_invocation_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
