"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .role import Role
from albus_sdk.types import BaseModel
from typing_extensions import TypedDict


class SetOrganizationMemberRoleRequestTypedDict(TypedDict):
    role: Role
    r"""A member's role in an organization."""


class SetOrganizationMemberRoleRequest(BaseModel):
    role: Role
    r"""A member's role in an organization."""
