"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from albus_sdk.types import BaseModel, UNSET_SENTINEL, UnrecognizedStr
from datetime import datetime
from pydantic import model_serializer
from typing import Literal, Optional, Union
from typing_extensions import NotRequired, TypedDict


SpendLineKind = Union[
    Literal[
        "model",
        "model_byok",
        "hardware",
    ],
    UnrecognizedStr,
]
r"""What was used: a model billed to your credits, a model called with your own provider credential, or the compute an invocation ran on.

"""


class SpendLineTypedDict(TypedDict):
    day: datetime
    r"""The UTC midnight starting the day this line covers."""
    kind: SpendLineKind
    r"""What was used: a model billed to your credits, a model called with your own provider credential, or the compute an invocation ran on.

    """
    usd: str
    r"""What this line cost, as a decimal USD string. Zero when the usage was free. On a model_byok line this is the usage valued at our model prices for reference; you paid the provider directly and no credits were charged.

    """
    provider_name: NotRequired[str]
    r"""The provider that served the model. Present on model and model_byok lines.

    """
    model_name: NotRequired[str]
    r"""The model that was called. Present on model and model_byok lines.

    """
    sku: NotRequired[str]
    r"""The compute item charged (e.g. \"invocation_second\"). Present on hardware lines.

    """
    input_tokens: NotRequired[int]
    r"""Prompt tokens sent, including cached ones."""
    cached_input_tokens: NotRequired[int]
    r"""Prompt tokens served from the provider's cache."""
    output_tokens: NotRequired[int]
    r"""Tokens the model generated."""
    thoughts_tokens: NotRequired[int]
    r"""Tokens the model spent reasoning."""
    wall_ms: NotRequired[int]
    r"""Milliseconds of compute time charged."""


class SpendLine(BaseModel):
    day: datetime
    r"""The UTC midnight starting the day this line covers."""

    kind: SpendLineKind
    r"""What was used: a model billed to your credits, a model called with your own provider credential, or the compute an invocation ran on.

    """

    usd: str
    r"""What this line cost, as a decimal USD string. Zero when the usage was free. On a model_byok line this is the usage valued at our model prices for reference; you paid the provider directly and no credits were charged.

    """

    provider_name: Optional[str] = None
    r"""The provider that served the model. Present on model and model_byok lines.

    """

    model_name: Optional[str] = None
    r"""The model that was called. Present on model and model_byok lines.

    """

    sku: Optional[str] = None
    r"""The compute item charged (e.g. \"invocation_second\"). Present on hardware lines.

    """

    input_tokens: Optional[int] = None
    r"""Prompt tokens sent, including cached ones."""

    cached_input_tokens: Optional[int] = None
    r"""Prompt tokens served from the provider's cache."""

    output_tokens: Optional[int] = None
    r"""Tokens the model generated."""

    thoughts_tokens: Optional[int] = None
    r"""Tokens the model spent reasoning."""

    wall_ms: Optional[int] = None
    r"""Milliseconds of compute time charged."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "provider_name",
                "model_name",
                "sku",
                "input_tokens",
                "cached_input_tokens",
                "output_tokens",
                "thoughts_tokens",
                "wall_ms",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
