"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .spendline import SpendLine, SpendLineTypedDict
from albus_sdk.types import BaseModel
from datetime import datetime
from typing import List
from typing_extensions import TypedDict


class SpendResponseTypedDict(TypedDict):
    since: datetime
    r"""The UTC midnight the lines start from, after widening `since` to a whole day.

    """
    until: datetime
    r"""The UTC midnight the lines stop before, after widening `until` to a whole day.

    """
    total_usd: str
    r"""The sum of every line charged to your credits, as a decimal USD string. Excludes model_byok lines.

    """
    lines: List[SpendLineTypedDict]
    r"""Ordered by day, then kind, provider, model, and sku."""


class SpendResponse(BaseModel):
    since: datetime
    r"""The UTC midnight the lines start from, after widening `since` to a whole day.

    """

    until: datetime
    r"""The UTC midnight the lines stop before, after widening `until` to a whole day.

    """

    total_usd: str
    r"""The sum of every line charged to your credits, as a decimal USD string. Excludes model_byok lines.

    """

    lines: List[SpendLine]
    r"""Ordered by day, then kind, provider, model, and sku."""
