"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from albus_sdk.types import BaseModel, UNSET_SENTINEL
from datetime import datetime
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class TokenTypedDict(TypedDict):
    r"""API token metadata. Never includes the token value."""

    id: str
    r"""Globally unique lookup identifier (the first segment of the token string)."""
    name: str
    r"""Human-readable display name for the token."""
    created_at: datetime
    last_used_at: NotRequired[datetime]
    r"""Timestamp of the last time this token was used for authentication."""


class Token(BaseModel):
    r"""API token metadata. Never includes the token value."""

    id: str
    r"""Globally unique lookup identifier (the first segment of the token string)."""

    name: str
    r"""Human-readable display name for the token."""

    created_at: datetime

    last_used_at: Optional[datetime] = None
    r"""Timestamp of the last time this token was used for authentication."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["last_used_at"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
