"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from albus_sdk.types import BaseModel
from typing_extensions import TypedDict


class TraceFailureTypedDict(TypedDict):
    r"""Why an invocation failed, and what to show for it."""

    kind: str
    r"""Failure classification: \"crash\" (unexpected exit or signal), \"no_progress\" (the harness stalled and was force-killed), \"interrupted\" (the invocation could not continue), or \"internal\" (the invocation could not start).

    """
    message: str
    r"""The sentence recorded for this failure."""


class TraceFailure(BaseModel):
    r"""Why an invocation failed, and what to show for it."""

    kind: str
    r"""Failure classification: \"crash\" (unexpected exit or signal), \"no_progress\" (the harness stalled and was force-killed), \"interrupted\" (the invocation could not continue), or \"internal\" (the invocation could not start).

    """

    message: str
    r"""The sentence recorded for this failure."""
