"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .tracestatus import TraceStatus
from albus_sdk.types import BaseModel, UNSET_SENTINEL
from datetime import datetime
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class TraceSummaryTypedDict(TypedDict):
    r"""One agent invocation — what it ran, how it ended, and when."""

    invocation_key: str
    r"""The invocation's key — the value sent as its Idempotency-Key, or the one the server returned in that header when it was omitted.

    """
    session_id: str
    r"""The session this invocation belongs to."""
    status: TraceStatus
    r"""How an invocation or one of its attempts ended, or `RUNNING` while it is still in flight.

    """
    spans_expired: bool
    r"""Whether the invocation's spans have aged out. Spans are kept for the retention window (currently 90 days) from the invocation's start; the invocation itself is kept, so `status` and the fields beside it stay readable past it.

    """
    started_at: datetime
    r"""When the invocation was accepted."""
    agent_name: NotRequired[str]
    r"""Name of the agent the invocation ran (e.g. \"support-triage\"). Absent for an invocation made before agent names were recorded.

    """
    agent_revision: NotRequired[str]
    r"""The agent revision the invocation ran (e.g. \"a1b2c3d4\"). Absent for an invocation made before revisions were recorded.

    """
    ended_at: NotRequired[datetime]
    r"""When the invocation's outcome was recorded. Absent while it runs.

    """


class TraceSummary(BaseModel):
    r"""One agent invocation — what it ran, how it ended, and when."""

    invocation_key: str
    r"""The invocation's key — the value sent as its Idempotency-Key, or the one the server returned in that header when it was omitted.

    """

    session_id: str
    r"""The session this invocation belongs to."""

    status: TraceStatus
    r"""How an invocation or one of its attempts ended, or `RUNNING` while it is still in flight.

    """

    spans_expired: bool
    r"""Whether the invocation's spans have aged out. Spans are kept for the retention window (currently 90 days) from the invocation's start; the invocation itself is kept, so `status` and the fields beside it stay readable past it.

    """

    started_at: datetime
    r"""When the invocation was accepted."""

    agent_name: Optional[str] = None
    r"""Name of the agent the invocation ran (e.g. \"support-triage\"). Absent for an invocation made before agent names were recorded.

    """

    agent_revision: Optional[str] = None
    r"""The agent revision the invocation ran (e.g. \"a1b2c3d4\"). Absent for an invocation made before revisions were recorded.

    """

    ended_at: Optional[datetime] = None
    r"""When the invocation's outcome was recorded. Absent while it runs.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["agent_name", "agent_revision", "ended_at"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
