"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from albus_sdk.types import UnrecognizedStr
from typing import Literal, Union


TraceStatus = Union[
    Literal[
        "RUNNING",
        "SUCCEEDED",
        "FAILED",
        "CANCELED",
    ],
    UnrecognizedStr,
]
r"""How an invocation or one of its attempts ended, or `RUNNING` while it is still in flight. `CANCELED` means it was stopped on request before it answered.

"""
