"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .tokenusage import TokenUsage, TokenUsageTypedDict
from .tracestatus import TraceStatus
from albus_sdk.types import BaseModel, UNSET_SENTINEL
from datetime import datetime
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class TraceAttemptTypedDict(TypedDict):
    r"""One attempt of an invocation. An invocation is attempted again when an attempt cannot be finished, and every attempt starts the agent's work over: an attempt before the last one spent its own tokens and may have made tool calls whose effects stand, even though nothing it produced reached the invocation's output."""

    attempt: int
    r"""Which attempt this is, counting from 1. The last one is the attempt that produced the invocation's outcome, or the one still in flight, and the one whose spans come back unless `attempts=all` is requested.

    """
    status: TraceStatus
    r"""How an invocation or one of its attempts ended, or `RUNNING` while it is still in flight. `CANCELED` means it was stopped on request before it answered.

    """
    started_at: datetime
    r"""When the attempt began."""
    ended_at: NotRequired[datetime]
    r"""When the attempt ended. Absent while it runs."""
    usage: NotRequired[TokenUsageTypedDict]
    r"""Tokens consumed. Absent when none were recorded."""


class TraceAttempt(BaseModel):
    r"""One attempt of an invocation. An invocation is attempted again when an attempt cannot be finished, and every attempt starts the agent's work over: an attempt before the last one spent its own tokens and may have made tool calls whose effects stand, even though nothing it produced reached the invocation's output."""

    attempt: int
    r"""Which attempt this is, counting from 1. The last one is the attempt that produced the invocation's outcome, or the one still in flight, and the one whose spans come back unless `attempts=all` is requested.

    """

    status: TraceStatus
    r"""How an invocation or one of its attempts ended, or `RUNNING` while it is still in flight. `CANCELED` means it was stopped on request before it answered.

    """

    started_at: datetime
    r"""When the attempt began."""

    ended_at: Optional[datetime] = None
    r"""When the attempt ended. Absent while it runs."""

    usage: Optional[TokenUsage] = None
    r"""Tokens consumed. Absent when none were recorded."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["ended_at", "usage"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
