"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .traceattempt import TraceAttempt, TraceAttemptTypedDict
from .tracefailure import TraceFailure, TraceFailureTypedDict
from .tracespan import TraceSpan, TraceSpanTypedDict
from .tracestatus import TraceStatus
from albus_sdk.types import BaseModel, UNSET_SENTINEL
from datetime import datetime
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class TraceResponseTypedDict(TypedDict):
    r"""One agent invocation — what it ran, how it ended, and when."""

    invocation_key: str
    r"""The invocation's key — the value sent as its Idempotency-Key, or the one the server returned in that header when it was omitted.

    """
    session_id: str
    r"""The session this invocation belongs to."""
    status: TraceStatus
    r"""How an invocation or one of its attempts ended, or `RUNNING` while it is still in flight. `CANCELED` means it was stopped on request before it answered.

    """
    spans_expired: bool
    r"""Whether the invocation's spans have aged out. Spans are kept for the retention window (currently 90 days) from the invocation's start; the invocation itself is kept, so `status` and the fields beside it stay readable past it.

    """
    started_at: datetime
    r"""When the invocation was accepted."""
    session_position: int
    r"""Which invocation of its session this is, counting from 1 in the order they were created — the same number as the `inv` segment of every span's id, so you do not have to read an id to know which invocation you are holding. Invocations are only ever appended, so a position never changes.

    """
    spans: List[TraceSpanTypedDict]
    r"""A page of the invocation's spans, oldest first, from its latest attempt unless `attempts=all` asked for the earlier attempts as well. It can hold fewer than `limit`, or none at all, while `next_cursor` is present. Empty once `spans_expired` is true.

    """
    agent_name: NotRequired[str]
    r"""Name of the agent the invocation ran (e.g. \"support-triage\"). Absent for an invocation made before agent names were recorded.

    """
    agent_revision: NotRequired[str]
    r"""The agent revision the invocation ran (e.g. \"a1b2c3d4\"). Absent for an invocation made before revisions were recorded.

    """
    ended_at: NotRequired[datetime]
    r"""When the invocation's outcome was recorded. Absent while it runs.

    """
    failure: NotRequired[TraceFailureTypedDict]
    r"""Why the invocation ended without answering. Present only when `status` is `FAILED` or `CANCELED`, and readable past the retention window, since it comes from the invocation rather than its spans. Read it here rather than from `GET /traces`, which reports only that an invocation failed — listing a page of reasons costs a lookup per invocation on it.

    """
    attempts: NotRequired[List[TraceAttemptTypedDict]]
    r"""Every attempt of the invocation, oldest first, whichever attempts `spans` came from — so one entry means it ran once, and more than one means the attempts before the last produced nothing that reached its output, while still spending tokens and making any tool calls they made. Read them with `attempts=all`. Absent once `spans_expired` is true.

    """
    next_cursor: NotRequired[str]
    r"""Cursor for the next page. Pass it as `after` to fetch the following spans. Present whenever there may be more spans, however few this page returned; omitted once there are none left, including once `spans_expired` is true.

    """


class TraceResponse(BaseModel):
    r"""One agent invocation — what it ran, how it ended, and when."""

    invocation_key: str
    r"""The invocation's key — the value sent as its Idempotency-Key, or the one the server returned in that header when it was omitted.

    """

    session_id: str
    r"""The session this invocation belongs to."""

    status: TraceStatus
    r"""How an invocation or one of its attempts ended, or `RUNNING` while it is still in flight. `CANCELED` means it was stopped on request before it answered.

    """

    spans_expired: bool
    r"""Whether the invocation's spans have aged out. Spans are kept for the retention window (currently 90 days) from the invocation's start; the invocation itself is kept, so `status` and the fields beside it stay readable past it.

    """

    started_at: datetime
    r"""When the invocation was accepted."""

    session_position: int
    r"""Which invocation of its session this is, counting from 1 in the order they were created — the same number as the `inv` segment of every span's id, so you do not have to read an id to know which invocation you are holding. Invocations are only ever appended, so a position never changes.

    """

    spans: List[TraceSpan]
    r"""A page of the invocation's spans, oldest first, from its latest attempt unless `attempts=all` asked for the earlier attempts as well. It can hold fewer than `limit`, or none at all, while `next_cursor` is present. Empty once `spans_expired` is true.

    """

    agent_name: Optional[str] = None
    r"""Name of the agent the invocation ran (e.g. \"support-triage\"). Absent for an invocation made before agent names were recorded.

    """

    agent_revision: Optional[str] = None
    r"""The agent revision the invocation ran (e.g. \"a1b2c3d4\"). Absent for an invocation made before revisions were recorded.

    """

    ended_at: Optional[datetime] = None
    r"""When the invocation's outcome was recorded. Absent while it runs.

    """

    failure: Optional[TraceFailure] = None
    r"""Why the invocation ended without answering. Present only when `status` is `FAILED` or `CANCELED`, and readable past the retention window, since it comes from the invocation rather than its spans. Read it here rather than from `GET /traces`, which reports only that an invocation failed — listing a page of reasons costs a lookup per invocation on it.

    """

    attempts: Optional[List[TraceAttempt]] = None
    r"""Every attempt of the invocation, oldest first, whichever attempts `spans` came from — so one entry means it ran once, and more than one means the attempts before the last produced nothing that reached its output, while still spending tokens and making any tool calls they made. Read them with `attempts=all`. Absent once `spans_expired` is true.

    """

    next_cursor: Optional[str] = None
    r"""Cursor for the next page. Pass it as `after` to fetch the following spans. Present whenever there may be more spans, however few this page returned; omitted once there are none left, including once `spans_expired` is true.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "agent_name",
                "agent_revision",
                "ended_at",
                "failure",
                "attempts",
                "next_cursor",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
