"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from albus_sdk.types import BaseModel
from typing_extensions import TypedDict


class UpdateSecretRequestTypedDict(TypedDict):
    value: str
    r"""The new secret value."""


class UpdateSecretRequest(BaseModel):
    value: str
    r"""The new secret value."""
