"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .updatesecretrequest import UpdateSecretRequest, UpdateSecretRequestTypedDict
from albus_sdk.types import BaseModel
from albus_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UpdateSecretRequestRequestTypedDict(TypedDict):
    name: str
    body: UpdateSecretRequestTypedDict


class UpdateSecretRequestRequest(BaseModel):
    name: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    body: Annotated[
        UpdateSecretRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
