"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from albus_sdk.types import BaseModel
from typing_extensions import TypedDict


class WebSearchToolTypedDict(TypedDict):
    r"""Offers the model web search."""


class WebSearchTool(BaseModel):
    r"""Offers the model web search."""
