"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from albus_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class WhoamiResponseTypedDict(TypedDict):
    user_id: str
    r"""Unique user identifier"""
    email: str
    r"""User's email address"""
    name: NotRequired[str]
    r"""User's display name"""
    roles: NotRequired[List[str]]
    r"""User's roles"""
    issued_at: NotRequired[int]
    r"""Token issue timestamp (Unix epoch)"""
    expires_at: NotRequired[int]
    r"""Token expiration timestamp (Unix epoch)"""


class WhoamiResponse(BaseModel):
    user_id: str
    r"""Unique user identifier"""

    email: str
    r"""User's email address"""

    name: Optional[str] = None
    r"""User's display name"""

    roles: Optional[List[str]] = None
    r"""User's roles"""

    issued_at: Optional[int] = None
    r"""Token issue timestamp (Unix epoch)"""

    expires_at: Optional[int] = None
    r"""Token expiration timestamp (Unix epoch)"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["name", "roles", "issued_at", "expires_at"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
